### ISSUE TITLE
User Documentation

### ISSUE THREAD

**Issue by BenGalewsky** [ssl-hep/ServiceX#104]
_As a user of ServiceX I want documentation so I can use the service_

# Assumptions
1. On readthedocs
2. Includes API, client, and Qastl

**Comment by gordonwatts** [comment]
Adding some things to make sure they get included

- Make sure to mention that the namespace is required in a rucio DID (this gets me every time I start something new, and is a ATLAS centric issue, likely).
- How to understand all the errors in the API (preflight, DID, etc.) - so the user can figure out things!
