### ISSUE TITLE
Error Reporting

### ISSUE THREAD

**Issue by BenGalewsky** [ssl-hep/ServiceX#105]
# Story
_As an analyzer I want to receive reports of errors in my transformation so I can take corrective action_

# Assumptions
1. Ability to view entries in the dead letter queue
2. Visibility of exactly what went wrong in code generator

# Acceptance Criteria
3. All "Something went wrong" reports are replaced with more meaningful  messages

**Comment by gordonwatts** [comment]
For Acceptance Criteria I suggest we get a small number of errors for this round. Then as we find more things that frustrate users, we add to either this story or create new ones, depending. Here is a list to get a discussion started:

- General
   - An incorrect DID name
   - A malformed WebAPI request (e.g. missing a required entry in the JSON)
   - Provide bad access credentials
- xAOD Transform
   - Tries to access a xAOD collection that doesn't exist
   - Tries to call a method on an object that doesn't exist
   - Tries to call a method on an object with the wrong number of arguments
- uproot Transform
   - Ask for a leaf name that doesn't exist
   - Ask for a tree name that doesn't exist

**Comment by gordonwatts** [comment]
I'd like to add an error that will fail deep into the transform, and not on every single transform. Not sure how to name those... something that no matter how much preflight we do, we will get an explosion.

**Comment by BenGalewsky** [comment]
We need to make sure we can pick up on invalid dataset names - the DID finder should be able to report this back to the status message

**Comment by d-w-liu** [comment]
If asked to retrieve a dataset that has zero files, the ServiceX request never completes. Here is the log for the DID finder:

```
---->  {'request_id': '08f2c044-08c1-4f3c-9b6e-805cb01a8a1a', 'did': 'data17_13TeV:data17_13TeV.periodK.physics_Main.PhysCont.DAOD_STDM7.grp22_v01_p3713', 'service-endpoint': 'http://servicex-1594041060-servicex-app:8000/servicex/transformation/08f2c044-08c1-4f3c-9b6e-805cb01a8a1a'}
Dataset contains 0 files. Lookup took 0:00:01.613057
DID data17_13TeV:data17_13TeV.periodK.physics_Main.PhysCont.DAOD_STDM7.grp22_v01_p3713 - 0 Mb 0 Events in 0 files (0 skipped)
```

I triggered this request by sending the code:

```
def test_servicex_stress_capacity():
    dataset = ServiceXDataset('data17_13TeV:data17_13TeV.periodK.physics_Main.PhysCont.DAOD_STDM7.grp22_v01_p3713', max_workers = 100)
    query = ServiceXDatasetSource(dataset) \
        .SelectMany('lambda e: (e.Jets("AntiKt4EMTopoJets"))') \
        .Where('lambda j: (j.pt()/1000)>30') \
        .Select('lambda j: (j.pt())') \
        .AsPandasDF("JetPt") \
        .value()
    
    return query

stress_test = test_servicex_stress_capacity()
```

**Comment by gordonwatts** [comment]
It seemed like to us this was an edge case of the DID not found at all. Though in this case the DID finder didn't seem to report anything to the app...
