### ISSUE TITLE
Multiple DIDs in a Transform Request

### ISSUE THREAD

**Issue by BenGalewsky** [ssl-hep/ServiceX#113]
# Story
_As an analyzer I want to run a transform across multiple datasets so I can transform all of the events needed for my analysis_

# Assumptions
1. DID Property becomes a list
2. The root files in each of the datasets are broadly similar so the same transform makes sense

# Acceptance Criteria
1. Given I have a transform request with multiple DIDs when I submit the request then I should get back results in the same Kafka topic from all of the root files in those DIDs

**Comment by BenGalewsky** [comment]
I guess not, although multiple Kafka Topics is a little more fiddly to use

**Comment by kyungeonchoi** [comment]
I understand it is a very user specific request. I agree that this feature should be low priority, but certainly better to submit one transform request than multiple requests.

**Comment by gordonwatts** [comment]
Is it? Should the library that the users uses just do it? Or is it something the API should support?

**Comment by BenGalewsky** [comment]
Looks like this can be accomplished by just passing in a _container id_ instead of a _dataset id_. Rucio will just recursively find all of the files.

Closing this as "nothing to do"

**Comment by gordonwatts** [comment]
Yes -t hat is correct
