### ISSUE TITLE
Detailed Transformer Logging

### ISSUE THREAD

**Issue by BenGalewsky** [ssl-hep/ServiceX#121]
# Story
_As a serviceX developer I want to see detailed transformer job logging so I can diagnose problems and find bottlenecks_

# Assumptions
1. Create a new table in the database just for status messages
2. Status records should include the transformer pod name to make it easy to look for logs
3. Record when a file gets picked up for transform
4. Record failures
5. Record when the file is complete

# Acceptance Criteria
1. While a job is running I can see which files are currently being transformed and find the log file entries for the transformer.
2. I can analyze the database and find the longest running transform and report the pod and filename

**Comment by gordonwatts** [comment]
@BenGalewsky how can I get at this data?
