### ISSUE TITLE
Upgrade Uproot CodeGen to func_adl_uproot 0.11 

### ISSUE THREAD

**Issue by BenGalewsky** [ssl-hep/ServiceX#123]
as @masonproffitt mentioned in the analysis systems meeting, there is a new version of qastle (0.7) which handles all the previously missing python operators (%, **, //, &, |, ^, <<, >>) and a new version of func_adl_uproot (0.11) which now handles all these and the if/else ternary expressions correctly

**Comment by gordonwatts** [comment]
@masonproffitt, do you need to do something here?

**Comment by masonproffitt** [comment]
I don't think so? If I do, someone will need to let me know what it is.
