### ISSUE TITLE
ServiceX Command Line Needs Namespace Parameter

### ISSUE THREAD

**Issue by BenGalewsky** [ssl-hep/ServiceX#127]
# Problem
The serviceX command line can install secrets into the cluster, however it depends on the default namespace. If you wish to install secrets in another namespace you are out of luck!

**Comment by gordonwatts** [comment]
There is the `--namespace` option. The thing is that you can pick up a default namespace from the current config, and it would be cool if the command line did. When I interact with k8 via `kubectl` I don't need to specify my namespace - it just picks it up from the config files. That was the feature I was looking for. :-)

**Comment by BenGalewsky** [comment]
Ok - closing issue

**Comment by gordonwatts** [comment]
Was this closed because it was fixed?
