### ISSUE TITLE
Authenticate into ServiceX

### ISSUE THREAD

**Issue by BenGalewsky** [ssl-hep/ServiceX#13]
# Story
_As an analyzer I want to authenticate into the service so I can securely access data I'm entitled to_

# Acceptance Criteria
1. User completes log in process
2. System can tell if user is authorized for Atlas or CMS data

# Assumptions
1. Log on with Globus Auth

How do we know if the user is ATLAS or CMS

**Comment by ivukotic** [comment]
Auth using globus is there I will test it today. More appropriate auth later.

**Comment by ivukotic** [comment]
@BenGalewsky can you try logging into the service ?

**Comment by ivukotic** [comment]
works for me. closing.
