### ISSUE TITLE
Improve Uproot transformer serialization 

### ISSUE THREAD

**Issue by kyungeonchoi** [ssl-hep/ServiceX#131]
# Story
Current uproot transformer performs the following steps for the serialization of data:
1. Awkward Table returned from `generated_transformer.py`
2. Convert Awkward Table to Pandas DataFrame (DF)
3. Convert Pandas DF to Arrow
4. Save Arrow as Parquet or stream to Kafka

Remove unnecessary step(s) and implement the new method suggested by Jim Pivarski to improve the performance.

# Acceptance Criteria
1. Better performance of Uproot transformer

**Comment by kyungeonchoi** [comment]
Awkward supports a direct conversion from `awkward.Table` to Arrow (`awkward.toarrow`), but the layout of `awkward.Table` returned by `generated_transformer.py` is not compatible with this function. It has to be top-level ChunkedArrays to be converted to Arrow.

Two solutions:
1. Immediate: convert `awkward.Table` to `awkward1.Table` and then back to `awkward.Table`. This fixes the layout issue of the original `awkward.Table`. Now `awkward.toarrow` should work. `awkward1 >= 0.2.19` supports this method.
2. Near future: Uproot will produce `awkward1.Table` and awkward1 will produce Arrow (https://github.com/scikit-hep/awkward-1.0/pull/224)

Quick benchmark of Awkward Table to Arrow serialization for the 9904 (row) x 20 (column) Awkward table (tested at UC River):
- Current: 7.95 sec
- Immediate solution: 0.01 sec

Significant improvement is expected for large tables.

**Comment by jpivarski** [comment]
Although it's technically closed, work on scikit-hep/awkward-1.0#224 hasn't stopped. I've taken over for Anish and I'm touching up his work as scikit-hep/awkward-1.0#263. It should be ready pretty soon—these are the final dottings and crossings of i's and t's.
