### ISSUE TITLE
Minio Retention Policy

### ISSUE THREAD

**Issue by BenGalewsky** [ssl-hep/ServiceX#133]
# Story
_As a ServiceX administrator I want old transform outputs to be deleted so I can manage storage costs_

# Assumptions
1. There are Minio settings that can be applied to files to enforce retention policy
2. Configurable for a site via Helm values.yaml

# Acceptance Criteria
1. How will we know when this story is complete

**Comment by gordonwatts** [comment]
Acceptance criteria should include regenerating automatically. I think this will require caching.

**Comment by BenGalewsky** [comment]
I think one step at a time. We need to get the object store resources under control. Next step is reproduction upon request. Let's put those ideas into #314 (very crude story, but a starting point)
