### ISSUE TITLE
TCut Library to write Qastle for ServiceX

### ISSUE THREAD

**Issue by gordonwatts** [ssl-hep/ServiceX#137]
# Story
As an analyzer I want to write a simple `TCut` based expression to do simple selection of data from any of the `func_adl` backends supported by `servicex` so that I can quickly get to a point of streaming columnar data into my analysis.

# Assumptions
1. `servicex` serves from the `uproot` and the `xAOD` backends.
1. This library won't wrap the frontend library, rather you'll call this and then use it with the servicex frontend library.

# Acceptance Criteria
1. This library will translate the `TCut` style of selections into `qastle`
1. Both object cuts and event-level cuts are implemented
1. This `qastle` can be passed directly to the `servicex` frontend library along with a dataset name
1. This can be supported for both the xAOD and the uproot backends

**Comment by alexander-held** [comment]
In this context the [`formulate` package](https://github.com/scikit-hep/formulate) might be useful.

**Comment by gordonwatts** [comment]
There is also this package: https://github.com/lukasheinrich/pyhfinput/

But I think @kyungeonchoi already has code that does this. So this might be a matter of packaging!

**Comment by kyungeonchoi** [comment]
The wrapper I wrote for [ServiceXforTRExFitter](https://github.com/kyungeonchoi/ServiceXforTRExFitter/blob/master/ServiceXTCutToQastleWrapper.py) is based on the old version of `qastle` and requires some work (lack of ternary operation and robustness). I will update that and make a standalone package.

**Comment by gordonwatts** [comment]
This sounds like a great plan, @kyungeonchoi . Please let us know of progress and if there is something that can be done to help!

**Comment by kyungeonchoi** [comment]
I've uploaded the version 0.1 of `tcut_to_qastle` package to the PyPI. It should work with uproot transformer out of the box.
