### ISSUE TITLE
Transformation Pods should have up to date GRID machine certificates at all times.

### ISSUE THREAD

**Issue by gordonwatts** [ssl-hep/ServiceX#148]
**Describe the bug**
The GRID certificate infrastructure requires up-to-date set of public machine certificates. Unfortunately, these periodically expire. The current transformer pods are made with these certificates baked in. So at some point, when they get old enough, the pods start to fail to access some of the grid sites.

**To Reproduce**

1. Use an older transformation pod
1. Use servicex to make a request
1. Watch the pod fail with "Authentication failure" - which might mean a lot of things, but in this case, it means the machine public certs are out of date.

**Expected behavior**

File should be accessed by the transformer.

**Screenshots**

```
Package.EventLoop        INFO    created submission directory /home/atlas/rel/build/bogus
Package.EventLoop        INFO    submitting job in /home/atlas/rel/build/bogus
Package.EventLoop        INFO    Running sample: ANALYSIS
Package.EventLoop        INFO    xAODInput = 1
Package.EventLoop        INFO    Opening file root://atlas.dcache.nikhef.nl:1094//pnfs/nikhef.nl/data/atlas/atlasdatadisk/rucio/mc16_13TeV/89/89/DAOD_EXOT15.17545540._000008.pool.root.1   
TNetXNGFile::Open         ERROR   [FATAL] Auth failed
/build/atnight/localbuilds/nightlies/21.2/athena/PhysicsAnalysis/D3PDTools/SampleHandler/Root/ToolsOther.cxx:62:exception: failed to open file: root://atlas.dcache.nikhef.nl:1094//pnfs/nikhef.nl/data/atlas/atlasdatadisk/rucio/mc16_13TeV/89/89/DAOD_EXOT15.17545540._000008.pool.root.1
```

This is log file from the transformer [0.4](https://hub.docker.com/layers/sslhep/servicex_func_adl_xaod_transformer/0.4/images/sha256-2d1c8b33220a99a42c212f6b2fbfa112fb805c7afbf9f80a2ca616a42f41adf0?context=explore).

**Additional context**

The simplest fix may be to just build the image on a cron job every two days or so.

**Comment by gordonwatts** [comment]
Another way to do this is mount machine grid certs as something shared the way it is done with the x509 cert right now, and then have servicex run the fetchcrl job periodically and update the store in real-time.

**Comment by ivukotic** [comment]
my 2 cents: having certs in the image is a really bad idea as it allows anybody to access all of the ATLAS data by simply using the image. having a cert mounted as a volume is completely OK, but it should not be a machine cert but a service certificate. One should ask for a service certificate, just like we have for other services. That way one can do proper accounting.

**Comment by BenGalewsky** [comment]
@ivukotic - we are actually talking about CRLs, and not the x509 grid certs. The X509 certs are not in the image and are vended by the X509 Secret Service in the cluster.
