### ISSUE TITLE
Specifying Transformer Version Container

### ISSUE THREAD

**Issue by gordonwatts** [ssl-hep/ServiceX#149]
# Story
_As a user I want to not have to worry about specific versions of the transformer container so I can write code that doesn't need updating when `servicex` changes version numbers._

# Assumptions
1. The transformer is more tightly tied to the `codegen` container than anything else.
1. Currently, the `servicex` library has hard-wired an xAOD backend transformer container version number.
1. When the servicex version is upgraded, the container you are supposed to use is also upgraded often.
1. Unless the user upgrades their `servicex` library, they will not get bumped and run the risk of all their transforms failing for no obvious (to them) reason.
1. There are different backends and code-gen (think ATLAS xAOD, ROOT file uproot, CMS TreeMaker)

# Acceptance Criteria
1. The user does not have to specify an image name to get the default latest-and-greatest transformer if they are aimed at the uproot or xAOD or whatever version of servicex endpoint.
1. If someone (a developer) wants, they can still specify a specific version of the transformer container

**Comment by gordonwatts** [comment]
Possible approaches: tags. You could say "default" for the image, and it would take whatever the installation had as the default image. Otherwise, it would use docker as it currently does.

**Comment by BenGalewsky** [comment]
How often do the experiment base images (such atlasanalysisbase) change? For reproducibility, it would be important to record which specific version of the transformer produced the results. We could do this default behavior and then include the resolved image tag in the `/servicex/transformation/<string:request_id>` request, which is now the request that returns the Minio endpoint.

**Comment by alexander-held** [comment]
> How often do the experiment base images (such atlasanalysisbase) change?

Roughly once a week https://hub.docker.com/r/atlas/analysisbase/tags, although in my experience analyzers don't constantly change the base every time a new tag comes out. This is partially caused by the processing of all relevant files for an analysis on the grid taking longer than a week and only being done a few times a year.

**Comment by gordonwatts** [comment]
This is a good point. You do want to use an analysis image tag that is consistent across your analysis - otherwise, you run the risk have having two different sets of corrections applied to your data. We have two axes here: one set of version numbers that affects the operation (the code that interacts with Servicex) and the user doesn't care about. The other affects the data (the analysis release tag), and the user does care about that.

**Comment by ponyisi** [comment]
Q: how is the codegen code currently selected? (How would a developer making their own container select the codegen step?)

My preference here would be that the developer of each transformer provides a file that maps between a short user string (e.g. ATLASxAOD-21.2.140-1.0) and the full codegen/transformer image names/tags. Not entirely sure how I would want to manage the semantics of the version in the user string (or whether it's even necessary to have a standard between different transformers?)

**Comment by gordonwatts** [comment]
I agree - something like that - and it should be stored in github somewhere.

Currently, the codegen version number is specified in the `helm` chart. So it is tied to the version and flavor of servicex you are running. And it can be modified by a `values.yaml`, so even if it is in git, that doesn't mean that is actually what is being run.

So an obvious flaw here.

**Comment by BenGalewsky** [comment]
@gordonwatts - I'm going to implement this as a new GET endpoint at `/servicex` it returns a little JSON document that looks like this:
```
{
    "app-version": "develop",
    "default-transformer": "sslhep/servicex_func_adl_xaod_transformer:1.0.0-RC.3",
    "code-gen": "sslhep/servicex_code_gen_func_adl_xaod:develop"
}
```

app-version comes out of the app's setup.py

The default transformer is a new helm value, and the the code-gen value is the setting for the code-gen pod's docker image.

Does this seem good? Any other info we might want to include here?

**Comment by gordonwatts** [comment]
This looks good to me.

Do both of these appear in the database when you request a transformer status?

The codegen is part of the reproducibility - so it should be "logged."
