### ISSUE TITLE
Add Slack webhook for signup alerts

### ISSUE THREAD

**Issue by mweinberg2718** [ssl-hep/ServiceX#152]
# Story
As a ServiceX admin I want to be notified when a new user signs up for the service.

The current authentication method is sufficient but bare-bones; in addition it would be good to have a Slack webhook or mailgun to alert admins when a new person signs up

**Comment by BenGalewsky** [comment]
Please split this into two stories -- since they are independent, much easier to schedule and manage bite-sized enhancements
