### ISSUE TITLE
Implement Globus Auth

### ISSUE THREAD

**Issue by AndrewEckart** [ssl-hep/ServiceX#169]
# Story
_As a ServiceX user I want to authenticate with Globus (or some other federated identity provider) so I can use my institutional identity_

# Assumptions
1. Globus Auth will enable users to login with their identity from a number of supported institutional providers (CERN and most universities). We will identify users by their Globus ID, and store this in the PostgreSQL database.
2. Each user will be issued a JWT refresh token by ServiceX, which will be stored in the database and visible on the web frontend.
3. Users will store their ServiceX refresh token a local `.servicex` file. The Python frontend client will use this to obtain access tokens and use these for authorization.
4. If a user leaks their refresh token, we can enable them to generate a new one on the website. Only the current refresh token can be used to obtain access tokens, so the old refresh token is no longer usable.

# Acceptance Criteria
1. Globus Auth is implemented
2. Web frontend allows users to sign in, create/view/edit their user profiles, and obtain their ServiceX tokens. At least one of the following is supported: copy the refresh token to clipboard, download a `.servicex` file with the token pre-populated, or copy and run a script which stores the refresh token in `~/.servicex` automatically
3. Python frontend supports reading refresh tokens from `.servicex` config file. The refresh token is used to obtain an access token which the client uses to submit transformation requests.
4. The Flask app has an additional endpoint which enables authenticated users to click a button and generate a new refresh token, which is stored in the database. When an access token is requested, Flask checks the refresh token against the current one in the database, and only issues an access token if there is a match.

**Comment by BenGalewsky** [comment]
How will users obtain their tokens? It's tricky to interact with an OAuth2 source without a web browser? We need to make sure it can work from a python program

**Comment by AndrewEckart** [comment]
> How will users obtain their tokens? It's tricky to interact with an OAuth2 source without a web browser? We need to make sure it can work from a python program

My understanding is that we can keep the existing JWT infrastructure and use that to generate the tokens. I don't have much knowledge in this area, so maybe @cnweaver can elaborate.

**Comment by cnweaver** [comment]
It's not possible to go through an OAuth2 flow without a web browser (which a limitation I've never personally liked). However, there are a couple of ways to deal with this: The [Globus SDK](https://globus-sdk-python.readthedocs.io/en/stable/) does support ["Native App Login"](https://globus-sdk-python.readthedocs.io/en/stable/examples/native_app/) (which actually has nothing to do with native code), but that is more suited to tools which want authorization to use Globus services  specifically. The other option is just require users to log into the ServiceX App to be issued some token specific to ServiceX (which could just be the JWTs used today), and then do something to put those where the forntend library can use them. There's a lot of flexibility possible here in terms of what the tokens are, how long they last, where they are stored, and what the interface looks like to the user. 

Just to illustrate one possibility in this space, for [SLATE](https://slateci.io) we do the following: Users initially authenticate via the Globus OAuth2 flow (including their actual Identity Provider's system, whatever that is). The SLATE API then generates a token to assign to them; at present this token is an opaque blob of data (just the output of a cryptographic RNG). Users can write this token to a file (canonically ~/.slate/token) which the command line `slate` tool will read. Like `ssh`, the tool will stop and complain if the token file does not have suitably restrictive permissions, and making a location in the home directory the default somewhat reduces the probability of a user checking a token into public version control, etc. All requests to the API must have a token attached (as a query parameter, currently) or they are rejected. If a token is attached, it is looked up in the SLATE database to see if it really is a valid, previously issued token. 

You can no doubt see many variations which are possible here: The tokens could have associated expiration dates, or could be structured (e.g. JWT) and carry cryptographically signed expirations inside them. The 'token' as seen by the user could in fact be the ServiceX App's current pair of an access token and a refresh token. This would require Gordon to make a few changes in his library, as there would no longer be a username, password pair at all, and if the refresh token is expired or not present he would have to direct the user to go get one in a browser session.

**Comment by gordonwatts** [comment]
I do not know much about the workflow here. To me Globus does not mean JWT, but means rather things like `voms-proxy-init`. In which case, the user has to do this, and then there is a known "place" to pick up the authenticated token.

In general, nothing should be put in the `.servicex` file unless it will remain constant for months or years at a time. Most tokens you get for access have a range of validity of order hours, or a day or two. Those are generally written in their own file in some well-known place, and the ServiceX frontend should pick them up there.

**Comment by bbockelm** [comment]
I don't think we should be using Globus auth here as the IdP -- strategically, we should use CILogon instead as it is open-source and lines up with what other folks in the community are doing.

**Comment by AndrewEckart** [comment]
Updated with latest discussion on Slack.

**Comment by BenGalewsky** [comment]
Let's add an assumption that the user model in the database can work with multiple OAuth providers. I think that would entail a generic userID field and a provider field that says where it came from?

**Comment by AndrewEckart** [comment]
> Let's add an assumption that the user model in the database can work with multiple OAuth providers. I think that would entail a generic userID field and a provider field that says where it came from?

Isn't this reinventing the wheel a little bit with what Globus does? They already maintain a set of identities, where each identity has an associated name, email, provider ID, provider name, and "subject" (user id in OAuth terms).

It seems like what we were discussing earlier is abstracting one level higher and supporting multiple federated identity solutions (i.e. Globus alongside something else). While possible, I think we can kick that down the road, at which point we can do a database migration.

**Comment by bbockelm** [comment]
Yes - but that's highly specific to the Globus provider - which is a big step backwards in portability and effectively not in use by ServiceX's target audience.
