### ISSUE TITLE
A transform that fails to transform files should clean up the transform deployment

### ISSUE THREAD

**Issue by gordonwatts** [ssl-hep/ServiceX#176]
**Describe the bug**
If a transform fails because some number of files fail, the transform never completes, and the transform pods are not cleaned up

**To Reproduce**
1. Submit a transform against a dataset that has some number of bad files in it (bad means a file that cannot be correctly loaded by the system). An example dataset I've been having this trouble with: `mc16_13TeV:mc16_13TeV.361106.PowhegPythia8EvtGen_AZNLOCTEQ6L1_Zee.deriv.DAOD_STDM3.e3601_e5984_s3126_r10201_r10210_p3975_tid20425969_00`.
2. Let the transform run. Some number of fo files will fail.
3. Eventually, all files will be done, one way or the other.

**Expected behavior**
The deployment for the transform should be deleted, and all transform pods should be terminated in k9.

**Additional context**
Workaround: delete the deployment by had, for example, by `kubectl delete deployment/transformer-8716d52a-974e-4f1d-beed-3425485d8f9b`

**Comment by BenGalewsky** [comment]
Do these files show up in the failed count?

**Comment by gordonwatts** [comment]
Yes.

**Comment by BenGalewsky** [comment]
I think this is resolved via many enhancments over time
