### ISSUE TITLE
ServiceX needs a logo

### ISSUE THREAD

**Issue by AndrewEckart** [ssl-hep/ServiceX#184]
# Story
_As a ServiceX user I want to recognize ServiceX by its logo_

# Assumptions
1. Someone on the team has graphic design skills

# Acceptance Criteria
1. We have consensus on a logo design
2. Logo is an SVG so we can scale it to any resolution and [use it as a favicon](https://css-tricks.com/svg-favicons-and-all-the-fun-things-we-can-do-with-them/).

**Comment by BenGalewsky** [comment]
Done - ![logo](https://raw.githubusercontent.com/ssl-hep/ServiceX/develop/docs/img/ServiceX-WhiteText-Transparent.png)
