### ISSUE TITLE
Accessing the uproot backend

### ISSUE THREAD

**Issue by gordonwatts** [ssl-hep/ServiceX#186]
# Story
As a user I want to submit a query against flat-root files and use the `uproot` backend to process those files, extract the data, and have `servicex` ship them back to me.

# Assumptions
1. User submits a well formatted query
1. Dataset is flat root files layed out the proper way for the `uproot` backend.
1. User uses the `servicex_frontend` python library (`servicex`).

# Acceptance Criteria
1. `ServiceX` returns data that can be unpacked by the user's python analysis script.

# Current status

Currently`servicex` expects an extra web api parameter, `tree_name`. This is passed on, along with the `selection` parameter the code-gen module of `servicex`.

# Proposal

Move to a system where only `selection` is passed on to `codegen`. Each new `codegen` will receive its full configuration via the `selection` parameter: no special case parameters for each new backend. This work will not only get `uproot` working, but it will also define the API for any future `codegen` operations (there is other work to do, of course).

This is a mega (??) issue - the work will be done in a bunch of other issues:

- [x] `func_adl` needs to generate the proper `qastle`
    - This work is occurring in [`func_adl_servicex`](https://github.com/iris-hep/func_adl_servicex), which contains a `servicex` adaptor for `func_adl`.
- [x] The `uproot` code generator needs to pull the tree name from the `qastle`, not from the `servicex` internal API
- [ ] `tree_name` should be cleaned out of the current `servicex` internal code
- [ ] A test should be implemented in the global testing stuff to make sure this works.

**Comment by BenGalewsky** [comment]
@gordonwatts is this still relevant?

**Comment by gordonwatts** [comment]
This is now done! We can close it!
