### ISSUE TITLE
Transformer Output File Format Options

### ISSUE THREAD

**Issue by BenGalewsky** [ssl-hep/ServiceX#225]
# Story
_As an analyzer I want the option of generating a ROOT file or a Parquet file for my transformed output so I can use the tools of my choice downstream_

# Assumptions
1. Add a new argument to the ServiceXDataset constructor to set the output format. Use a python enumeration to constrain the valid values
2. This value will be passed to ServiceX in the `result-format` property
3. Delete the `arrow` value for this in the app json parser
4. Add result_format argument to the transform_single_file scripts produced by the code generators
5. The xAOD transformer can only write root files
6. The uproot transformer can write Root or Parquet files
7. There will be logic in the sidecar transformer that will consult the transformer's capabilities file to decide if the requested format can be passed to the transform_single_file script
8. If not, then code in the sidecar, using uproot will transform the result that the transformer _can_ produce to the format requested by the user.See  PR #475 by @ponyisi] for guidance how to save awkward array as Root
9. Add integration test that exercises the new synchronous serviceX frontend API

# Acceptance Criteria
1. Use the integration test queries to generate one of each type of output for both transformers

# Tasks

- [ ] Add result_format option to ServiceXDataset. Make this a Python enum to make type checking available in the library. @talvandaalen

**Comment by ponyisi** [comment]
Hi Ben,

Just conceptually - imagine I was a non-HEP person and wanted to make a transformer of, I don't know, FITS files to HDF5, bypassing this translation framework. Would this be accommodated?

Best,
Peter

**Comment by BenGalewsky** [comment]
There is a bit of a tradeoff between openness and usability. This story imagines creating an enum of valid values. This prevents users from being frustrated by misspelling the output formats and not catching that til the transformer picks up the request.

HDF5 would have to be compiled in to allow users to deploy a transformer that accepts that. Of course it's possible that the app could interrogate the code generators to see what formats they support...

This wouldn't require user breaking changes, so I suggest we stick with the current plan and implement the more dynamic approach when the use case comes up.

**Comment by ponyisi** [comment]
@BenGalewsky No complaints about keeping things relatively simple for now - I just would caution against designing a system which couples the core frontend too closely to the details of the transformers. I would also suggest that the transformer be able to tell the sidecar to pass through the result transparently.
