### ISSUE TITLE
Dead Letter Queue for Error Causing Root Files

### ISSUE THREAD

**Issue by BenGalewsky** [ssl-hep/ServiceX#23]
# Story
_As an analyzer I want bad root files to be reported on a dead letter queue so I can complete my analysis and know which files were not completely included_

# Acceptance Criteria
1. _Given_ I have a job, _when_ it is submitted _then_ I should see a dead-letter queue created for the request_id
2. _Given_ I have a submitted job, _when_ an exception is found in a root file, _then_ I should see an entry for the root file in the dead letter queue and the offending file entry is removed from the transformer queue

# Assumptions

**Comment by robrwg** [comment]
Most analyses won't be considered complete until all of the files in the dataset have been analyzed.   Typically a job which has problems reading input data is marked as failed and retried up to some max number of attempts.  How does the dead-letter queue scheme differ?

**Comment by BenGalewsky** [comment]
Naturally, we can retry before putting something onto the dead letter queue, but what if we need to flush the file from XCache - we could put it back on the queue and try again later. 

What if the file is bad at the origin, we need to record this securely and then have some later process to request a fix. 

What if the file uncovered a bug in the transformer? The benefit of a dead letter queue is that it makes it easy to replay just the ones that failed using whatever mechanism we choose.

**Comment by robrwg** [comment]
Wouldn't a database recording state progression of the request be a better solution?

**Comment by BenGalewsky** [comment]
If you use a database then you have to re-implement all of the queue semantics for replaying. Why do that when we have a perfectly good queue technology. What is the benefit of a database for this?

**Comment by robrwg** [comment]
I don't know enough about queue technology to know what it offers, how it makes job management easier than tracking via a database.  Willing to be convinced - if this is something simple to implement, let's do it and see how it works.   (I believe @ivukotic 's version already does this but I could be mistaken.)

**Comment by BenGalewsky** [comment]
It's the basis of the new version and also works reliably. RabbitMQ is part of the helm chart. Gordon used it for his FuncADL analysis and was delighted by how much code he was able to throw away by relying on a supported queue manager

**Comment by robrwg** [comment]
Happy that we can use tools like RabbitMQ to reduce code writing, but that misses the point of my question.  I do not have a clear picture of how the dead letter queue fits into someone's analysis.

**Comment by BenGalewsky** [comment]
@robrwg just think of it as a database of failed root files. What we do with this information is up for discussion. With completion of this issue, we now have a robust place to record failures.

**Comment by BenGalewsky** [comment]
This story has been implemented in the following Pull Requests:

* [ServiceX_Transformer PR 29](https://github.com/ssl-hep/ServiceX_transformer/pull/29)
* [ServiceX_DID_Finder PR 5](https://github.com/ssl-hep/ServiceX-DID-finder/pull/5)

Tested on River with 10TB dataset as specified in the [Postman collection]( https://github.com/ssl-hep/ServiceX_App/blob/develop/ServiceXTest.postman_collection.json) checked into the ServiceX_App Repo. 

Once the transformers could survive corrupt ROOT files or other exceptions we discovered a couple of other weak links in the workflow. This led to changes in 
[DID Finder](https://github.com/ssl-hep/ServiceX-DID-finder/pull/5)

We than re-ran the 10TB dataset several times and confirmed that the same files were flagged as failures.
