### ISSUE TITLE
Autoscaling

### ISSUE THREAD

**Issue by ivukotic** [ssl-hep/ServiceX#238]
* Autoscaling should be turned on by default.
* Users should not be able to request number of CPUs
* targeted CPU utilization should be set to 0.2 or 0.3 since transformers are quite inefficient.
* documentation should be updated to clarify that the k8s cluster need to be able to run eg. kubectl top nodes

**Comment by robrwg** [comment]
Wondering if there is a blocker here of some sort, or perhaps was this already accomplished?
