### ISSUE TITLE
Build a Python based ROOT -> Arrow buffer transformer

### ISSUE THREAD

**Issue by gordonwatts** [ssl-hep/ServiceX#25]
## Currently

The xAOD code writes out a simple ROOT file. Here, simple is defined as a ROOT file that is not only readable by a vanilla version of ROOT, but contains no object columns (not event TLorentzVectors). The ROOT file is copied to a xrootd server after it is generated.

## Why Change

ServiceX uses arrow buffers to communicate the output of the transformer to the next stage of the system (kafka).

## Change To

The code that generates the ROOT file runs very fast (less than one minute for an 8 GB input file, for example, when no calibrations are required). The fastest way to get this feature in is to write a small python 2 program that reads the ROOT file with uproot, and then writes with appropriate chunk size to the arrow buffer, and ships the data to the appropriate place.

A future work item might be to write arrow buffers while running the C++ code, but that is more work as it will require writing and integrating the arrow buffer filling in C++.

**Comment by robrwg** [comment]
@mweinberg2718 can you update here your progress?

**Comment by lgray** [comment]
If it's needed, here's an example from earlier experiments with spark and coffea (when we had to convert file types).

https://gist.github.com/lgray/dbb545716d97528bbd09933929ff5a56

Arrow buffer filling in C++ is a very small delta, and not that much faster than python.
