### ISSUE TITLE
The AST that selects the columns should be in text format

### ISSUE THREAD

**Issue by gordonwatts** [ssl-hep/ServiceX#26]
_As an Analyzer I want to specify a list of columns in an extensible language representation so I can extract the columns I need for my analysis with a future path to more extensive transformations_

## Acceptance Criteria
1. A README documenting how a selection is specified 
2. A real world example of selecting columns

## Currently

The user builds a `python3` Abstract Syntax Tree (AST). This AST is translated into C++ code. The AST contains information about the dataset, selection cuts, and columns to be eventually extracted. The AST is currently `pickled`, and then base64 encoded when it is sent to the server.

## Why Change

There are a host of reasons. This was chosen because it was the simplest as we were building up an experimental version. The big ones driving this change now are:

- Pickle is a known security hole
- You can't figure out what is being written by looking at the message being sent to a server.
- Extra data that python needs, but a model like this do not, gets carried along.

## Change To

We will use a text representation of the AST. For example, the Select operation might look like `Select(source, (lambda a (code))` or similar.

**Comment by masonproffitt** [comment]
`ast.dump()` does most of this work for us. We just need to decide what to drop. Here's an example of `ast.dump()` on a query I pulled straight from some of my tests:
```python
Where(source=Select(source=AwkwardSourceStream(),
                    selection=Lambda(args=arguments(args=[arg(arg='e',
                                                              annotation=None)],
                                                    vararg=None,
                                                    kwonlyargs=[],
                                                    kw_defaults=[],
                                                    kwarg=None,
                                                    defaults=[]),
                                     body=Call(func=Attribute(value=Name(id='awkward'),
                                                              attr='Table'),
                                               args=[Dict(keys=[Str(s='eventNumber'), Str(s='jet_pT')],
                                                          values=[Attribute(value=Name(id='e',
                                                                                       ctx=Load()),
                                                                            attr='eventNumber',
                                                                            ctx=Load()),
                                                                  Attribute(value=Name(id='e',
                                                                                       ctx=Load()),
                                                                            attr='CalibJet_pT',
                                                                            ctx=Load())])]))),
      filter=Lambda(args=arguments(args=[arg(arg='x',
                                             annotation=None)],
                                   vararg=None,
                                   kwonlyargs=[],
                                   kw_defaults=[],
                                   kwarg=None,
                                   defaults=[]),
                    body=Subscript(value=Name(id='x'),
                                   slice=Index(value=Compare(left=Call(func=Attribute(value=Compare(left=Attribute(value=Name(id='x',
                                                                                                                              ctx=Load()),
                                                                                                                   attr='jet_pT',
                                                                                                                   ctx=Load()),
                                                                                                    ops=[Gt()],
                                                                                                    comparators=[Num(n=1000)]),
                                                                                      attr='count_nonzero',
                                                                                      ctx=Load()),
                                                                       args=[],
                                                                       keywords=[]),
                                                                                                    ops=[Gt()],
                                                                                                    comparators=[Num(n=0)])))))
```
`AwkwardSourceStream()` represents the actual data source, so we'll have to figure out how we want to handle that. We can certainly get rid of `ctx` everywhere (and it will always be `Load()` unless we need assignment). `args` can be flattened and simplified to get rid of `arguments`, `annotation`, `arg`, `vararg`, `kwonlyargs`, `kw_defaults`, `kwarg`, and `defaults`. Then I would get something like:
```python
Where(source=Select(source=AwkwardSourceStream(),
                    selection=Lambda(args=['e'],
                                     body=Call(func=Attribute(value=Name(id='awkward'),
                                                              attr='Table'),
                                               args=[Dict(keys=[Str(s='eventNumber'), Str(s='jet_pT')],
                                                          values=[Attribute(value=Name(id='e'),
                                                                            attr='eventNumber'),
                                                                  Attribute(value=Name(id='e'),
                                                                            attr='CalibJet_pT')])]))),
      filter=Lambda(args=['x'],
                    body=Subscript(value=Name(id='x'),
                                   slice=Index(value=Compare(left=Call(func=Attribute(value=Compare(left=Attribute(value=Name(id='x'),
                                                                                                                   attr='jet_pT'),
                                                                                                    ops=[Gt()],
                                                                                                    comparators=[Num(n=1000)]),
                                                                                      attr='count_nonzero'),
                                                                       args=[]),
                                                                                                    ops=[Gt()],
                                                                                                    comparators=[Num(n=0)])))))
```
From here I don't see obvious things that would make sense to remove or simplify.

**Comment by gordonwatts** [comment]
@masonproffitt and I and @emma had a discussion about this earlier today - he is going to try to write up an even simpler one (similar to the list stuff we've talked about) and see what this would look like.

**Comment by masonproffitt** [comment]
For going to something Lisp-y, I get this:
```python
(Where (Select AwkwardSourceStream()
               (Lambda (List 'e')
                       (Dict (List (Str 'eventNumber')
                                   (Str 'jet_pT'))
                             (List (Attribute (Name 'e')
                                              'eventNumber')
                                   (Attribute (Name 'e')
                                              'CalibJet_pT')))))
       (Lambda (List 'x')
               (Subscript (Name 'x')
                          (Index (Compare (Count (Attribute (Compare (Attribute (Name 'x')
                                                                                'jet_pT')
                                                                     (List Gt)
                                                                     (List (Num 1000)]))))
                                          (List Gt)
                                          (List (Num 0)))))))
```
It's prettier, but definitely harder to understand for debugging without the field names. Which is fine if it's not intended to be read directly.

**Comment by gordonwatts** [comment]
Possible changes:

1. Get rid of list - assume every (...) is a space separated list.
1. Variable names as bar things rather than strings
1. The dict is a "nice thing" that is in the user interface. Perhaps we remove it by the time it gets to the actual bottom layer (with a transformer, like the ones I've got for tuples and I need to write for this brilliant idea you have on dictionaries).

I started to do the translation myself, but the dict has totally confused me here (part of the reason I think we should not have it at this low level).

**Comment by masonproffitt** [comment]
All right, I think this is shaping enough to start trying to go bottom-up and get specific and technical. Ben suggests that we start with getting a Select working. I would propose that we have the following s-expressions:

- String literals: identical to Python's single-quoted or double-quoted strings without prefixes or formatting
- Variables (names): identical to Python's identifiers (but with no reserved keywords)
- Attributes: `(attr <object> <attribute name>)`
  - `object` is a variable, attribute, or function call
  - `attribute name` is a string literal
- Lists: `(list <item>*)`
  - Zero or more `item`s, space separated.
  - `item` is a literal, variable, `attr`, or function call
- Lambdas: `(lambda <argument names> <expression>)`
  - `argument names` is a `list` of variables
- Function calls: `(call <function> <argument>*)`
  - `function` is an attribute or lambda
  - Zero or more `argument`s, space separated
- Select: `(Select <source> <selector>)`
  - `source` is some representation of the data source--not sure what this should look like
  - `selector` is a lambda with one argument

**Comment by masonproffitt** [comment]
> Get rid of list - assume every (...) is a space separated list.

I don't think we want to get rid of `list`. That could easily cause collisions with AST node names.

> Variable names as bar things rather than strings

I'm not sure what "bar things" are, but I do think we can get away with treating variable names like Lisp (without quotes).

> The dict is a "nice thing" that is in the user interface. Perhaps we remove it by the time it gets to the actual bottom layer (with a transformer, like the ones I've got for tuples and I need to write for this brilliant idea you have on dictionaries).

I think we can at least leave it out for now for simplicity.

**Comment by gordonwatts** [comment]
Ok - I've done a bit more. I got confused about your original query - I think there was a "Where" missing. So I've re-written it in two forms, one with the straight select, and one with the straight Where. First without a filter operation:

```
awkward_array_stream
    .Select("lambda e: (e.eventNumber, e.CalibJet_pT)")\
    .AsColumns(("eventNumber" "jet_pT"))
```
Becomes:
```
AsColumns(
    (Select 
        awkward_array_stream
        (lambda e (e.eventNumber, e.CalibJet_pT))
    )
    ("eventNumber" "jet_pT")
)
```

And,
```
awkward_array_stream
    .Where("lambda e: (e.jet_pT.Where(lambda j: j > 1000).Count() > 0"))
    .Select("lambda e: (e.eventNumber, e.CalibJet_pT)")\
    .AsColumns(("eventNumber" "jet_pT"))
```

Becomes
```
AsColumns(
    (Select 
        (Where 
            awkward_array_stream
            (lambda e (Count (Where (e.jet_pT (lambda j (> j 1000))))))
        )
        (lambda e (e.eventNumber, e.CalibJet_pT))
    )
    ("eventNumber" "jet_pT")
)
```

Two things to note here:
1. Compared to your version, the Where was moved first. 
1. The references to the dict were removed

A transform on the AST, without regard to the back-end, I think, can be done to make these changes happen. This keeps the back-end much simpler.

BTW, I love your idea of using dicts like this, so I am definitely interested in writing the AST transformer that gives us that. I learned the hard way (from the C# project) that it is crucial to keep as much out of the code generation phase as possible. If you just looked at my bug history it would tell you the tail of woe for not doing that. :-)

**Comment by gordonwatts** [comment]
Ok - Mason (he doesn't show up in the @ list, is he not on this repo yet?) has convinced me we need a list predicate to avoid namespace collisions between variables and functions. We also agreed that the shorthand "a.b" is the same as (attr a b), but a lot easier to read - but still unique. So, with that in mind, and also fixing one "bug" I have in the above expression (I left a "," in there), this might become:

```
awkward_array_stream
    .Select("lambda e: (e.eventNumber, e.CalibJet_pT)")\
    .AsColumns(("eventNumber" "jet_pT"))
```
Becomes:
```
AsColumns(
    (Select 
        awkward_array_stream
        (lambda e (list e.eventNumber, e.CalibJet_pT))
    )
    (list "eventNumber" "jet_pT")
)
```

And,
```
awkward_array_stream
    .Where("lambda e: (e.jet_pT.Where(lambda j: j > 1000).Count() > 0"))
    .Select("lambda e: (e.eventNumber, e.CalibJet_pT)")\
    .AsColumns(("eventNumber" "jet_pT"))
```

Becomes
```
AsColumns(
    (Select 
        (Where 
            awkward_array_stream
            (lambda e (Count (Where (e.jet_pT (lambda j (> j 1000))))))
        )
        (lambda e (list e.eventNumber e.CalibJet_pT))
    )
    (list "eventNumber" "jet_pT")
)
```

**Comment by masonproffitt** [comment]
Is `AsColumns()` in functional_adl? I don't have anything like it in my backend. Shouldn't the return format be determined by the lambda in `Select()`? I can make the lambda return either a list or a dictionary, so `AsColumns` seems unnecessary to me. If it's a kludge to get dictionary-like behavior, we could just put a `dict` at the outer level and not have to introduce an extra node type.

I can accommodate everything else in your example if I add the following to the previous list of s-expressions:

- Number literals: identical to Python's real number literals
- Unary operators: `(<operator> <operand>)`
  - `operator` is one of: `+`, `-` (arithmetic); `not` (boolean)
- Binary operators: `(<operator> <left operand> <right operand>)`
  - `operator` is one of: `+`, `-`, `*`, `/` (arithmetic); `<`, `<=`, `==`, `!=`, `>`, `>=` (comparison); `and`, `or` (boolean)
- Where: `(Where <source> <predicate>)`
  - `source` is the same as for `Select`
  - `predicate` is a lambda with one argument, returning a single value

One potential issue is that this leaves out a `bool` literal. It's possible to just use numbers and implicitly cast to boolean values as `!= 0` when necessary. If we add boolean literals, that brings up collision problems again.

**Comment by masonproffitt** [comment]
I can think of a couple reasons to potentially keep a node equivalent to Python's `ast.Name`, which represents the name of a variable/object:

- We could guarantee that collisions with the AST language would *never* happen.
  - This means we can have literals other than numbers, strings, and variable names (so we could have boolean literals like `True` and `False`)
- It would preserve symmetry with how attributes are dealt with. Attributes must be represented by strings to avoid ambiguity:
  - Consider a case in which two variables have been defined, `x` and `y`. Then what does `(attr x y)` mean? If you allow the attribute name to be interpreted literally as "y", then you've completely hidden the variable `y` here. So the second argument of `attr` must be a string. Then `(attr x y)` means the attribute of `x` whose name is the string stored in the variable `y`. This is different from `x.y` in your semantics, which is equivalent to `(attr x "y")`.

**Comment by gordonwatts** [comment]
We should definitely have a set of reserved words - like `True` and `False`.

And I'm ok with not doing 'x.y'.

**Comment by masonproffitt** [comment]
I started putting together something with specifications and some examples, based on the discussion here: https://github.com/masonproffitt/ast-language. It will need to be extended, but I think this is consistent with everything we've agreed upon so far and is certainly capable of handling `Select` to extract columns.

**Comment by BenGalewsky** [comment]
Can we close this, @gordonwatts ?

**Comment by gordonwatts** [comment]
@masonproffitt - you should close this if you think we are done.

**Comment by masonproffitt** [comment]
I'm not able to close it, but I think it's done.
