### ISSUE TITLE
Downloaded Servicex.yaml has incorrect scheme 

### ISSUE THREAD

**Issue by BenGalewsky** [ssl-hep/ServiceX#266]
**Describe the bug**
When I download a servicex.yaml file from the site, it contains the URL for the serviceX instance. Due to ingress controller setup, this url has `http` scheme instead of `https`. This doesn't work since flask will not accept bearer tokens that are in requests that lack ssl encryption.
 
**To Reproduce**
1. Log into serviceX web page
2. Click. on _Profile_
3. Select _Download config_ action
4. Inspect the resulting servicex.yaml file

**Expected behavior**
The `endpoint` property should have an https schema

**Additional context**
This is generated in`servicex/web/servicex_file.py` - it uses `request.url_root` to find the url. Not sure if there is a more reliable property in the request? Otherwise we may need to assume https?

**Comment by sthapa** [comment]
Are there any circumstances where we want the scheme to be http?  The `servicex/tests/web/test_servicex_file.py` has tests that look for `http://localhost` as the endpoint.  Would `http://localhost` show up in use?

**Comment by AndrewEckart** [comment]
> Are there any circumstances where we want the scheme to be http? The `servicex/tests/web/test_servicex_file.py` has tests that look for `http://localhost` as the endpoint. Would `http://localhost` show up in use?

Yes, localhost is the only use case for http. This route is only available to authenticated users, and Globus Auth will only redirect to https urls. The sole exception is that they will redirect to `http://localhost`. But this does come up - it's common to use localhost with port forwarding for test / dev deployments, even if they have auth enabled.

**Comment by sthapa** [comment]
Okay, gotcha.  I have an initial draft fix for this, just want to do some local testing before pushing the code to github and creating a fix.  Basic idea is to use the `urllib` library to parse `url_root` and then update the scheme to https if the url is using http and does not have localhost in the `netloc` field.

**Comment by BenGalewsky** [comment]
I wonder if there are any properties on the request object that hold the original un-rewritten url that might say what the user started out with?

**Comment by sthapa** [comment]
There's a few http headers that might work (`Host`, `Origin`, `Forwarded`), I'm not sure how going through a proxy might affect this though.

**Comment by AndrewEckart** [comment]
Found a place in the codebase where I did this: `scheme = 'http' if 'localhost' in request.base_url else 'https'`.

It's in `servicex/web/auth_callback.py`. Not sure if this is more or less robust than other approaches. Maybe we should abstract this to a utility function.

**Comment by sthapa** [comment]
I separated my code out into a separate function to make unit testing easier.   I can move that to the `web/test_utils.py` file if that'd be a more appropriate location

**Comment by BenGalewsky** [comment]
@sthapa - I think it would be a good exercise to add a print statement with the `Host`, `Origin` and `Forwarded`, build a docker image and deploy it to river cluster and see what actually happens out in the wild. There might be a tidy solution, but only if it works with the proxy, etc. In any event you should gain experience using the River cluster expertly.

**Comment by sthapa** [comment]
Okay, let me work on that today then
