### ISSUE TITLE
User Supplied Transformer Title

### ISSUE THREAD

**Issue by BenGalewsky** [ssl-hep/ServiceX#269]
# Story
_As an analyzer I want to provide a short title for my transform requests so I can identify them later_

# Assumptions
1. New parameter to the transformation request
2. Persisted to DB
3. Provide a reasonable default value to maintain backward compatibility
4. Change service_frontend library accordingly
5. Title shows up in the Transformation dashboard

# Acceptance Criteria
1. How will we know when this story is complete

**Comment by gordonwatts** [comment]
It should be ok if the title is not unique.

**Comment by BenGalewsky** [comment]
@AndrewEckart - is this issue now complete?

**Comment by AndrewEckart** [comment]
Steps 1, 2, 3, and 5 were completed in ssl-hep/ServiceX_App#105. Step 4 is not - see ssl-hep/ServiceX_frontend#163.

**Comment by gordonwatts** [comment]
@AndrewEckart - I think this can be closed now!

**Comment by AndrewEckart** [comment]
> @AndrewEckart - I think this can be closed now!

Agreed - all goals have been completed.
