### ISSUE TITLE
Move current github repos containing the C++ transformer into new homes

### ISSUE THREAD

**Issue by gordonwatts** [ssl-hep/ServiceX#27]
## Currently

All repos exist under the user @gordonwatts.

## Why Change

Now that the code will be used by more than just me, it is time to move it.

## Change To

- Repo [func_adl_cpp_writer](https://github.com/gordonwatts/func_adl_cpp_writer) will move to the ssl-hep repo. This contains the top-level driver that will communicate with the ServiceX app.
- Repo [func_adl_cpp_runner](https://github.com/gordonwatts/func_adl_cpp_runner) will move to the ssl-hep repo. This contains teh top-level driver that will communicate with the ServiceX app.
- Repo [functional_adl](https://github.com/gordonwatts/functional_adl) will be split into three seperate repo's, and will be in the iris-hep namespace/organization:
    - func_adl - client code that is included by someone that wants to access data from ServiceX, and a second namespace package that gives access to lots of ast utilities. This is code likely useful for many backends.
    - func_adl_xAOD - Contains the code that converts the simplified ast into C++ code and script files appropriate for running on xAOD files in an analysis container produced by the experiment (e.g. runner, above). It also contains the single bit of front-end code that is used to submit a request over the wire. It will, of course, need to be adapted for ServiceX's API.

**Comment by gordonwatts** [comment]
The first client-size repo appears here: https://github.com/iris-hep/func_adl. If I can figure out how to do python packaging correctly, other sub-packages will appear there as well.

**Comment by gordonwatts** [comment]
Next task to getting this done - flake8 and travis for CI as with the rest of service X.

**Comment by gordonwatts** [comment]
Ok - all of those now have travis CI and flake8 running for each build, and a code-coverage badge. The test coverage isn't too bad for the first last ones (where most of the code is): >80%.

**Comment by gordonwatts** [comment]
@BenGalewsky and @mweinberg2718 - I assume this is the proper place to park this issue now that I think I'm done with this step. What happens next?

**Comment by robrwg** [comment]
@BenGalewsky @mweinberg2718 can you clarify next steps for @gordonwatts ?

**Comment by gordonwatts** [comment]
I think we are done with this now. Is there any review that needs to happen before this gets closed?
