### ISSUE TITLE
Support Multiple DID Finders

### ISSUE THREAD

**Issue by gordonwatts** [ssl-hep/ServiceX#273]
# Story
As a user, I'd like to be able to supply a DID to ServiceX that will fetch files from different sources. For example:

- Specifies a rucio dataset name
- Specifies a URL to fetch the list of files
- Specifies a list of files.

ServiceX would then spin up transformers and run over this list of files.

# Assumptions
1. The current way of specifying a DID continues to work (e.g. a rucio dataset name)
2. A DID finder service is written to render the DID into the list of files for the particular method the user wants
3. There will be multiple DID finders,  each reading from their own `did_requests` queue
4. A new app config setting will specify the default _scheme_ to use if none specified. To maintain backward compatibility, this would default to `rucio::`

# Acceptance Criteria
1. A query that looks as it currently does (no modification to the DID) works.
2. Two DID finders can work together
3. Two queries can be submitted using each DID finder.

# Approach

Reimagine the `did` field in the JSON request. The following are then (possible) valid DID's. The following two will work out of the box:

- `"did": "mc15_13TeV:mc15_13TeV.361106.PowhegPythia8EvtGen_AZNLOCTEQ6L1_Zee.merge.DAOD_STDM3.e3601_s2576_s2132_r6630_r6264_p2363_tid05630052_00"`
- `"did": "rucio://mc15_13TeV:mc15_13TeV.361106.PowhegPythia8EvtGen_AZNLOCTEQ6L1_Zee.merge.DAOD_STDM3.e3601_s2576_s2132_r6630_r6264_p2363_tid05630052_00"`

Some possible others - a DID finder would be needed to be written for these:

- `"did": "http://my.catalog.edu/ds1"` - The DID finder will make a request to the URL and fetch a file list that will be fed to ServiceX.
- `"did": "filelist://files_list?file=file1&file=file2"` - where `file1` and `file2` are encoded URL's that the ServiceX transformers can access.
- `"did": "cernopendata://1507"` - look up is done against CERN's opendata infrastructure.

Which DID finder is used by default will be configurable in the `helm` chart - so different communities can use different defaults.

For reference, a current request to the ServiceX API looks like the following:

```
{
	"did": "data17_13TeV:data17_13TeV.periodK.physics_Main.PhysCont.DAOD_STDM7.grp22_v01_p3713",
	"selection": "(call ResultTTree (call Select (call SelectMany (call EventDataset (list 'localds:bogus')) (lambda (list e) (call (attr e 'Jets') 'AntiKt4EMTopoJets'))) (lambda (list j) (/ (call (attr j 'pt')) 1000.0))) (list 'JetPt') 'analysis' 'junk.root')",
	"image": "sslhep/servicex_xaod_cpp_transformer:develop",
	"result-destination": "object-store",
	"result-format": "root-file",
	"chunk-size": 7000,
	"workers": 100
}
```

**Comment by gordonwatts** [comment]
@ponyisi - could you update the above to list some specific examples of local files - where they are stored?

**Comment by ponyisi** [comment]
@gordonwatts - an example dataset would be root://utatlas.its.utexas.edu//data_ceph/onyisi/20190222_study_top_radiation/user.ponyisi.410471.PhPy8EG_A14_ttbar_hdamp258p75_allhad.merge.190305_output.root/user.ponyisi.17322819._000XXX.output.root, where XXX = 001 to 100.

**Comment by ponyisi** [comment]
BTW I'm almost 100% sure the backend supports this already - at least, the option to send this information is defined in the REST API.

**Comment by ponyisi** [comment]
Hi Gordon - this is interesting - would it be expected that the user construct the URL including the dataset? Works for me I suppose...

**Comment by gordonwatts** [comment]
> Hi Gordon - this is interesting - would it be expected that the user construct the URL including the dataset? Works for me I suppose...

I had thought, actually, that was what you were talking about. Perhaps you can be a little more specific? Like an example? :-)

**Comment by ponyisi** [comment]
My original thought was that there would be two JSON keys - 'did' and 'did-lookup-url' maybe - and ServiceX would concatenate them (then the meaning of 'did' would be maintained as an abstract dataset name, instead of perhaps being a name and perhaps being a URL).

**Comment by gordonwatts** [comment]
So you mean:

```
{
	"did": "dataset1",
        "did-lookup-url": "http://catalog_machine.org/",
	"selection": "(call ResultTTree (call Select (call SelectMany (call EventDataset (list 'localds:bogus')) (lambda (list e) (call (attr e 'Jets') 'AntiKt4EMTopoJets'))) (lambda (list j) (/ (call (attr j 'pt')) 1000.0))) (list 'JetPt') 'analysis' 'junk.root')",
	"image": "sslhep/servicex_xaod_cpp_transformer:develop",
	"result-destination": "object-store",
	"result-format": "root-file",
	"chunk-size": 7000,
	"workers": 100
}
```

And that would turn into `http://catalog_machine.org/dataset1`? Reading your comment, would `dataset1` be expected to be unique accross all catalogs? I worry a little bit about that. Is there any other reason to split things like this?

**Comment by ponyisi** [comment]
I did mean that, yeah. I wouldn't expect `dataset1` to be unique across all catalogs, actually quite the reverse - I would expect there to be quite a few repeats (imagine e.g. two people call a dataset "ttbar"). Is the concern that you want to ensure that `did` is unique across all requests (and not the `(did, did-lookup-url)` combination)?

**Comment by gordonwatts** [comment]
Yeah - I don't think you can assure they are unique - I'm skeptical you can do that for exactly the reasons you mention. I was trying to get to the bottom of which way is better - split the URL or keep them the same? I like a whole URL if only because now the URL format isn't specified by ServiceX... but, rather, by the user.

BTW - should I add that the data is available without authorization?

**Comment by ponyisi** [comment]
I'm not entirely sure there's an awful lot to be gained from "URL format is specified by the user", since I think we're assuming that the pattern is ServiceX issues a HTTP GET to the URL, and is returned a JSON list of files for that dataset.  I suppose the user could have some mangling function they want to apply to generate the URL, but I don't see an enormous number of use cases.

My main reason for prefering them separate is that it makes the API clean: we don't overload "did" by requiring ServiceX to figure out if it is in the form of a URL or not. I'm always deeply suspicious of overload-resolution logic of this kind...

For the URL I think we can say that it won't need authentication. It's actually an interesting question about whether we require anonymous access for the data: I guess it's a reasonable starting point, but is it worth future-proofing the API with the ability to add auth data somehow?

**Comment by gordonwatts** [comment]
Ok perfect.

- not requiring authentication isn't about limiting future things - it is about limiting the work on this. In short - don't do extra work to support auth - that can be done when we have something concrete to work against.
- The above spec doesn't return JSON - it returns a set of lines, one dataset per line (see the spec above). If it is JSON, then we have to define what the JSON that comes back is.
- The reason I wanted to just write the HTTP was that that way the URL can take whatever form. For example, CERN open data won't really conform to the above: the DID finder internally doesn't work by just combining HTTP and dataset name. I suppose you could have the URL be something like "http:/catalog_machine.org/{did}" or similar. But even with CERN OpenData that won't work because getting the file list is a 2 step process. You start with the data set number, then you fetch the filelist name, and then you fetch the file list. There is no way to support all this without custom code - or handing a hard-coded URL to services so the user could support it, or building up a separate catalog web service that maps between the two. It would be nice to minimize how often you have to do that as that will be something many people want to avoid.

**Comment by BenGalewsky** [comment]
You know what? This could easily be done in the frontend... it could do the `requests` call and get back a list and pass that to ServiceX in the `file-list` property we already support. 
In the client code, we can encourage people to be as fancy as they want... we could provide some tooling to make some popular interfaces easy to use, but not needing to keep up to date in the server.

If we did implement this in the server then it would be a synchronous call inside the submit-transformation route, so there are no performance losses by keeping it in the client

**Comment by AndrewEckart** [comment]
> You know what? This could easily be done in the frontend... it could do the `requests` call and get back a list and pass that to ServiceX in the `file-list` property we already support.
> In the client code, we can encourage people to be as fancy as they want... we could provide some tooling to make some popular interfaces easy to use, but not needing to keep up to date in the server.
> 
> If we did implement this in the server then it would be a synchronous call inside the submit-transformation route, so there are no performance losses by keeping it in the client

This work would then have to be duplicated if someone decides to implement a C++ client or any other front end.

Edit: After reading more above, I think that the initial request actually belongs in user code, not in our libraries at all. We should just support passing a list of file URLs to create a transformation request, irrespective of the source of that list.

**Comment by ponyisi** [comment]
@gordonwatts - I think we're trying to solve two different problems... I'm looking at it as a way to allow people to provide a "custom" did-finder service external to ServiceX, and I think you're seeing it as a way to pass a list of files to ServiceX (where the user has effectively done the catalog lookup already).  In the OpenData example I would assume that this would be implemented as a custom service for the particular catalog.  If we are assuming that user code is already doing part of the lookup in a catalog itself then I really don't think there's any point in not doing the extra step and retrieving the file list on the client side a la @AndrewEckart .

Perhaps the best answer is indeed to just have a separate discussion about whether we can factor the did-finder API into a separate application that people could stand up for catalogs in general ... ?

**Comment by gordonwatts** [comment]
Ok - this might have degenerated to a chat at this point @ponyisi  (as in we need to do it face-to-face). But I'm thinking along the same lines too, I thought. I just do not understand the difference between splitting the URL in two or doing it as one. I like the "as one" because now the URL can be any format, whereas as two the URL must be directly appendable. From your point of view, I think the argument for two was not to overload the use of the DID JSON tag. Those I suppose we could just use "did-url" as the tag, and drop the did tag.

That isn't to say that @AndrewEckart 's suggestion of a file list isn't a bad one either!).

**Comment by gordonwatts** [comment]
I have updated the initial blurb above to reflect this conversation, please take a look!

**Comment by gordonwatts** [comment]
And after a discussion with @BenGalewsky , as this was starting to feel like it was grown in scope, we took a step back and re-imagined this as having multiple DID finders. And what DID finder was part of a deployment was up to the person doing the deployment. Please see the (yet again) updated description.

**Comment by ponyisi** [comment]
Qs on the updated description:
* would there be a central registry of supported url-like schemas? Or these would just be installed by the author of a new did-finder?
* is the intent to deprecate the file-list option in favor of putting things in a URL schema?

**Comment by BenGalewsky** [comment]
> Qs on the updated description:
> 
> * would there be a central registry of supported url-like schemas? Or these would just be installed by the author of a new did-finder?
It would vary by ServiceX deployment. Ideally the app could query the open queues in its local RabbitMQ. Failing that, we should have a list of valid schemes in the app config (set via the helm values.yaml)

> * is the intent to deprecate the file-list option in favor of putting things in a URL schema?
I don't see any reason not to. I'd encourage the various frontends to hide this and continue to support file lists as distinct python calls.
