### ISSUE TITLE
Accumulation of environment variables 

### ISSUE THREAD

**Issue by ivukotic** [ssl-hep/ServiceX#274]
Looking at environment variables like this:
kc exec  xaod-servicex-app-f75d5d8b-qcrp9 -n servicex -- printenv
shows that somehow deployments see environment variables from all other deployments in the same namespace.
I assume some of them are overwritten and this can lead to a huge mess.

output of the command above is:
`PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=xaod-servicex-app-f75d5d8b-qcrp9
APP_CONFIG_FILE=/opt/servicex/app.conf
AECKART_SERVICEX_APP_PORT=tcp://10.99.202.79:8000
AECKART_MINIO_SERVICE_PORT=9000
XAOD_RABBITMQ_PORT_25672_TCP=tcp://10.110.128.182:25672
XAOD_RABBITMQ_PORT_25672_TCP_ADDR=10.110.128.182
AECKART_POSTGRESQL_PORT_5432_TCP_PORT=5432
XAOD_CODE_GEN_PORT_8000_TCP=tcp://10.103.202.1:8000
AECKART_RABBITMQ_PORT_4369_TCP_PORT=4369
KUBERNETES_PORT_443_TCP=tcp://10.96.0.1:443
XAOD_POSTGRESQL_PORT_5432_TCP_ADDR=10.108.241.239
XAOD_RABBITMQ_PORT_5672_TCP_PORT=5672
UPROOT_ATLAS_CODE_GEN_PORT=tcp://10.110.150.253:8000
UPROOT_ATLAS_CODE_GEN_PORT_8000_TCP=tcp://10.110.150.253:8000
UPROOT_ATLAS_RABBITMQ_SERVICE_PORT_HTTP_STATS=15672
UPROOT_ATLAS_RABBITMQ_PORT_5672_TCP_PORT=5672
AECKART_POSTGRESQL_PORT_5432_TCP_ADDR=10.96.65.167
XAOD_POSTGRESQL_PORT_5432_TCP_PORT=5432
AECKART_RABBITMQ_PORT_5672_TCP_PROTO=tcp
XAOD_POSTGRESQL_SERVICE_HOST=10.108.241.239
XAOD_RABBITMQ_PORT=tcp://10.110.128.182:5672
UPROOT_ATLAS_CODE_GEN_PORT_8000_TCP_ADDR=10.110.150.253
XAOD_SERVICEX_APP_PORT_8000_TCP_ADDR=10.110.63.78
UPROOT_ATLAS_MINIO_SERVICE_HOST=10.104.227.16
UPROOT_ATLAS_RABBITMQ_PORT_5672_TCP_ADDR=10.101.88.222
AECKART_RABBITMQ_PORT_5672_TCP_PORT=5672
AECKART_RABBITMQ_PORT_5672_TCP_ADDR=10.98.107.231
AECKART_RABBITMQ_PORT_4369_TCP=tcp://10.98.107.231:4369
XAOD_SERVICEX_APP_SERVICE_PORT=8000
XAOD_MINIO_PORT_9000_TCP_PORT=9000
AECKART_RABBITMQ_SERVICE_PORT_HTTP_STATS=15672
AECKART_RABBITMQ_PORT_25672_TCP=tcp://10.98.107.231:25672
AECKART_RABBITMQ_PORT_15672_TCP_PORT=15672
DASK_SCHEDULER_PORT_80_TCP=tcp://10.104.248.136:80
XAOD_RABBITMQ_PORT_4369_TCP_ADDR=10.110.128.182
AECKART_SERVICEX_APP_PORT_8000_TCP_PROTO=tcp
XAOD_CODE_GEN_PORT=tcp://10.103.202.1:8000
AECKART_RABBITMQ_PORT_25672_TCP_PROTO=tcp
PHP_APACHE_PORT=tcp://10.102.96.249:80
XAOD_RABBITMQ_SERVICE_HOST=10.110.128.182
XAOD_RABBITMQ_SERVICE_PORT_HTTP_STATS=15672
UPROOT_ATLAS_RABBITMQ_SERVICE_PORT_DIST=25672
UPROOT_ATLAS_SERVICEX_APP_SERVICE_PORT=8000
AECKART_RABBITMQ_PORT_15672_TCP_PROTO=tcp
AECKART_CODE_GEN_SERVICE_PORT=8000
DASK_SCHEDULER_PORT_8786_TCP=tcp://10.104.248.136:8786
AECKART_MINIO_PORT_9000_TCP_PROTO=tcp
XAOD_MINIO_SERVICE_PORT_HTTP=9000
UPROOT_ATLAS_POSTGRESQL_PORT_5432_TCP=tcp://10.98.61.233:5432
KUBERNETES_PORT=tcp://10.96.0.1:443
UPROOT_ATLAS_CODE_GEN_SERVICE_PORT=8000
UPROOT_ATLAS_RABBITMQ_PORT_4369_TCP=tcp://10.101.88.222:4369
UPROOT_ATLAS_RABBITMQ_PORT_4369_TCP_PROTO=tcp
UPROOT_ATLAS_RABBITMQ_PORT_25672_TCP_ADDR=10.101.88.222
AECKART_POSTGRESQL_PORT_5432_TCP_PROTO=tcp
AECKART_MINIO_SERVICE_HOST=10.107.60.89
UPROOT_ATLAS_POSTGRESQL_SERVICE_PORT_TCP_POSTGRESQL=5432
UPROOT_ATLAS_SERVICEX_APP_PORT_8000_TCP=tcp://10.110.96.184:8000
XAOD_CODE_GEN_SERVICE_HOST=10.103.202.1
UPROOT_ATLAS_RABBITMQ_SERVICE_PORT_AMQP=5672
UPROOT_ATLAS_RABBITMQ_PORT_5672_TCP_PROTO=tcp
AECKART_MINIO_PORT_9000_TCP=tcp://10.107.60.89:9000
XAOD_MINIO_SERVICE_HOST=10.111.230.66
AECKART_RABBITMQ_PORT_4369_TCP_ADDR=10.98.107.231
XAOD_RABBITMQ_PORT_5672_TCP_ADDR=10.110.128.182
XAOD_POSTGRESQL_SERVICE_PORT_TCP_POSTGRESQL=5432
XAOD_RABBITMQ_SERVICE_PORT=5672
XAOD_RABBITMQ_PORT_15672_TCP_PROTO=tcp
UPROOT_ATLAS_MINIO_PORT_9000_TCP_PROTO=tcp
UPROOT_ATLAS_MINIO_PORT_9000_TCP_ADDR=10.104.227.16
AECKART_MINIO_PORT_9000_TCP_ADDR=10.107.60.89
KUBERNETES_SERVICE_PORT=443
XAOD_POSTGRESQL_PORT_5432_TCP_PROTO=tcp
UPROOT_ATLAS_RABBITMQ_PORT_15672_TCP_PORT=15672
XAOD_CODE_GEN_SERVICE_PORT=8000
UPROOT_ATLAS_SERVICEX_APP_PORT_8000_TCP_PROTO=tcp
AECKART_CODE_GEN_PORT_8000_TCP_PROTO=tcp
KUBERNETES_SERVICE_PORT_HTTPS=443
DASK_SCHEDULER_PORT_80_TCP_ADDR=10.104.248.136
XAOD_RABBITMQ_PORT_5672_TCP_PROTO=tcp
AECKART_POSTGRESQL_PORT_5432_TCP=tcp://10.96.65.167:5432
AECKART_MINIO_PORT=tcp://10.107.60.89:9000
AECKART_RABBITMQ_SERVICE_HOST=10.98.107.231
AECKART_CODE_GEN_PORT=tcp://10.99.116.206:8000
DASK_SCHEDULER_SERVICE_PORT_DASK_WEBUI=80
XAOD_RABBITMQ_PORT_4369_TCP_PORT=4369
XAOD_RABBITMQ_PORT_25672_TCP_PORT=25672
UPROOT_ATLAS_CODE_GEN_SERVICE_PORT_TCP=8000
UPROOT_ATLAS_RABBITMQ_SERVICE_PORT_EPMD=4369
AECKART_MINIO_SERVICE_PORT_HTTP=9000
XAOD_CODE_GEN_SERVICE_PORT_TCP=8000
AECKART_RABBITMQ_PORT_5672_TCP=tcp://10.98.107.231:5672
XAOD_RABBITMQ_SERVICE_PORT_EPMD=4369
UPROOT_ATLAS_POSTGRESQL_SERVICE_PORT=5432
XAOD_RABBITMQ_SERVICE_PORT_AMQP=5672
UPROOT_ATLAS_RABBITMQ_SERVICE_PORT=5672
AECKART_POSTGRESQL_SERVICE_HOST=10.96.65.167
PHP_APACHE_SERVICE_HOST=10.102.96.249
DASK_SCHEDULER_SERVICE_PORT_DASK_SCHEDULER=8786
UPROOT_ATLAS_MINIO_SERVICE_PORT_HTTP=9000
UPROOT_ATLAS_RABBITMQ_PORT=tcp://10.101.88.222:5672
AECKART_SERVICEX_APP_SERVICE_HOST=10.99.202.79
XAOD_MINIO_PORT_9000_TCP_ADDR=10.111.230.66
AECKART_RABBITMQ_PORT_15672_TCP=tcp://10.98.107.231:15672
AECKART_CODE_GEN_PORT_8000_TCP_ADDR=10.99.116.206
PHP_APACHE_PORT_80_TCP=tcp://10.102.96.249:80
XAOD_SERVICEX_APP_SERVICE_PORT_TCP=8000
XAOD_RABBITMQ_PORT_25672_TCP_PROTO=tcp
XAOD_RABBITMQ_PORT_15672_TCP=tcp://10.110.128.182:15672
UPROOT_ATLAS_RABBITMQ_PORT_25672_TCP_PROTO=tcp
AECKART_SERVICEX_APP_PORT_8000_TCP=tcp://10.99.202.79:8000
XAOD_CODE_GEN_PORT_8000_TCP_ADDR=10.103.202.1
XAOD_MINIO_PORT_9000_TCP_PROTO=tcp
XAOD_SERVICEX_APP_SERVICE_HOST=10.110.63.78
UPROOT_ATLAS_POSTGRESQL_PORT_5432_TCP_PORT=5432
DASK_SCHEDULER_PORT_8786_TCP_PORT=8786
UPROOT_ATLAS_RABBITMQ_PORT_4369_TCP_ADDR=10.101.88.222
AECKART_SERVICEX_APP_PORT_8000_TCP_PORT=8000
UPROOT_ATLAS_POSTGRESQL_PORT_5432_TCP_PROTO=tcp
UPROOT_ATLAS_MINIO_PORT_9000_TCP_PORT=9000
XAOD_SERVICEX_APP_PORT_8000_TCP_PROTO=tcp
XAOD_POSTGRESQL_PORT=tcp://10.108.241.239:5432
XAOD_RABBITMQ_PORT_5672_TCP=tcp://10.110.128.182:5672
XAOD_RABBITMQ_PORT_15672_TCP_PORT=15672
UPROOT_ATLAS_CODE_GEN_PORT_8000_TCP_PORT=8000
UPROOT_ATLAS_SERVICEX_APP_PORT_8000_TCP_PORT=8000
AECKART_RABBITMQ_PORT_25672_TCP_ADDR=10.98.107.231
PHP_APACHE_PORT_80_TCP_ADDR=10.102.96.249
AECKART_CODE_GEN_SERVICE_HOST=10.99.116.206
UPROOT_ATLAS_RABBITMQ_PORT_25672_TCP_PORT=25672
UPROOT_ATLAS_RABBITMQ_PORT_15672_TCP_PROTO=tcp
UPROOT_ATLAS_SERVICEX_APP_PORT=tcp://10.110.96.184:8000
AECKART_CODE_GEN_PORT_8000_TCP=tcp://10.99.116.206:8000
DASK_SCHEDULER_SERVICE_PORT=8786
UPROOT_ATLAS_POSTGRESQL_SERVICE_HOST=10.98.61.233
DASK_SCHEDULER_PORT=tcp://10.104.248.136:8786
KUBERNETES_SERVICE_HOST=10.96.0.1
XAOD_MINIO_PORT=tcp://10.111.230.66:9000
PHP_APACHE_PORT_80_TCP_PROTO=tcp
UPROOT_ATLAS_RABBITMQ_PORT_4369_TCP_PORT=4369
AECKART_POSTGRESQL_SERVICE_PORT_TCP_POSTGRESQL=5432
AECKART_POSTGRESQL_PORT=tcp://10.96.65.167:5432
AECKART_SERVICEX_APP_SERVICE_PORT=8000
AECKART_SERVICEX_APP_PORT_8000_TCP_ADDR=10.99.202.79
AECKART_RABBITMQ_SERVICE_PORT_DIST=25672
UPROOT_ATLAS_CODE_GEN_SERVICE_HOST=10.110.150.253
KUBERNETES_PORT_443_TCP_PROTO=tcp
KUBERNETES_PORT_443_TCP_PORT=443
UPROOT_ATLAS_MINIO_SERVICE_PORT=9000
XAOD_MINIO_SERVICE_PORT=9000
XAOD_MINIO_PORT_9000_TCP=tcp://10.111.230.66:9000
UPROOT_ATLAS_POSTGRESQL_PORT=tcp://10.98.61.233:5432
XAOD_SERVICEX_APP_PORT=tcp://10.110.63.78:8000
XAOD_SERVICEX_APP_PORT_8000_TCP=tcp://10.110.63.78:8000
XAOD_SERVICEX_APP_PORT_8000_TCP_PORT=8000
DASK_SCHEDULER_PORT_8786_TCP_ADDR=10.104.248.136
KUBERNETES_PORT_443_TCP_ADDR=10.96.0.1
XAOD_RABBITMQ_PORT_4369_TCP_PROTO=tcp
UPROOT_ATLAS_RABBITMQ_PORT_5672_TCP=tcp://10.101.88.222:5672
PHP_APACHE_PORT_80_TCP_PORT=80
AECKART_RABBITMQ_PORT=tcp://10.98.107.231:5672
UPROOT_ATLAS_SERVICEX_APP_SERVICE_PORT_TCP=8000
AECKART_RABBITMQ_SERVICE_PORT_AMQP=5672
AECKART_RABBITMQ_SERVICE_PORT_EPMD=4369
UPROOT_ATLAS_RABBITMQ_SERVICE_HOST=10.101.88.222
UPROOT_ATLAS_MINIO_PORT=tcp://10.104.227.16:9000
UPROOT_ATLAS_MINIO_PORT_9000_TCP=tcp://10.104.227.16:9000
UPROOT_ATLAS_RABBITMQ_PORT_15672_TCP=tcp://10.101.88.222:15672
AECKART_MINIO_PORT_9000_TCP_PORT=9000
AECKART_RABBITMQ_SERVICE_PORT=5672
AECKART_CODE_GEN_PORT_8000_TCP_PORT=8000
XAOD_RABBITMQ_PORT_4369_TCP=tcp://10.110.128.182:4369
DASK_SCHEDULER_PORT_80_TCP_PORT=80
XAOD_RABBITMQ_PORT_15672_TCP_ADDR=10.110.128.182
AECKART_POSTGRESQL_SERVICE_PORT=5432
AECKART_RABBITMQ_PORT_25672_TCP_PORT=25672
PHP_APACHE_SERVICE_PORT=80
XAOD_POSTGRESQL_SERVICE_PORT=5432
XAOD_POSTGRESQL_PORT_5432_TCP=tcp://10.108.241.239:5432
XAOD_RABBITMQ_SERVICE_PORT_DIST=25672
UPROOT_ATLAS_CODE_GEN_PORT_8000_TCP_PROTO=tcp
UPROOT_ATLAS_RABBITMQ_PORT_25672_TCP=tcp://10.101.88.222:25672
XAOD_CODE_GEN_PORT_8000_TCP_PORT=8000
UPROOT_ATLAS_SERVICEX_APP_PORT_8000_TCP_ADDR=10.110.96.184
UPROOT_ATLAS_POSTGRESQL_PORT_5432_TCP_ADDR=10.98.61.233
XAOD_CODE_GEN_PORT_8000_TCP_PROTO=tcp
AECKART_RABBITMQ_PORT_4369_TCP_PROTO=tcp
AECKART_RABBITMQ_PORT_15672_TCP_ADDR=10.98.107.231
DASK_SCHEDULER_PORT_8786_TCP_PROTO=tcp
DASK_SCHEDULER_PORT_80_TCP_PROTO=tcp
UPROOT_ATLAS_RABBITMQ_PORT_15672_TCP_ADDR=10.101.88.222
AECKART_SERVICEX_APP_SERVICE_PORT_TCP=8000
UPROOT_ATLAS_SERVICEX_APP_SERVICE_HOST=10.110.96.184
AECKART_CODE_GEN_SERVICE_PORT_TCP=8000
DASK_SCHEDULER_SERVICE_HOST=10.104.248.136
LANG=C.UTF-8
GPG_KEY=0D96DF4D4110E5C43FBFB17F2D347EA6AA65421D
PYTHON_VERSION=3.6.12
PYTHON_PIP_VERSION=20.3.3
PYTHON_GET_PIP_URL=https://github.com/pypa/get-pip/raw/5f38681f7f5872e4032860b54e9cc11cf0374932/get-pip.py
PYTHON_GET_PIP_SHA256=6a0b13826862f33c13b614a921d36253bfa1ae779c5fbf569876f3585057e9d2
HOME=/home/servicex`

**Comment by BenGalewsky** [comment]
This is a [feature of Kubernetes](https://kubernetes.io/docs/concepts/containers/container-environment/) it makes environment variables of each port in the services in the namespace at the time the pod is started. I think it can be turned off, but I doubt it's hurting anything

**Comment by ivukotic** [comment]
ah I did not notice these are all services... let's close this one.
