### ISSUE TITLE
Deep links into read-the-docs from readme.md no longer work

### ISSUE THREAD

**Issue by gordonwatts** [ssl-hep/ServiceX#283]
The deep links into read-the-docs from the `readme.md` do not work properly. For example, `https://servicex.readthedocs.io/en/latest/requests/` should be `https://servicex.readthedocs.io/en/latest/user/requests/`. There are a few instances of this.

If this is a bug in the `README.md` let me know and I can make a quick pull request. But this might also be a bug in how the read-the-docs document is being produced, pushed.

**Comment by AndrewEckart** [comment]
Just a bug in the README, I'll fix it now
