### ISSUE TITLE
Make sure the transformer can run on the DID specification generated by ServiceX's DID Finder

### ISSUE THREAD

**Issue by gordonwatts** [ssl-hep/ServiceX#29]
## Currently

The transformer can run on anything that the EventLoop framework (Analysis) can take. This includes lots of options, including http, xroot, and, of course, file.

## Why Change

The DID finder, given a dataset, generates a set of files to access via XCache. I'm nervous something my code might not support it. So it needs to be tested.

## Change To

Get a valid XCache file that can be accessed and test. If it does not work, fix it.

**Comment by ivukotic** [comment]
Did finder always looks up files with --protocol root so it will always be something like:
root://xcache.mwt2.org:1094//root://dcache-atlas-xrootd-wan.desy.de:1094//pnfs/desy.de/atlas/dq2/atlaslocalgroupdisk/rucio/mc15_13TeV/8a/f1/DAOD_STDM3.05630052._000001.pool.root.1 or root://dcache-atlas-xrootd-wan.desy.de:1094//pnfs/desy.de/atlas/dq2/atlaslocalgroupdisk/rucio/mc15_13TeV/8a/f1/DAOD_STDM3.05630052._000001.pool.root.1

**Comment by gordonwatts** [comment]
Perfect, thank you.

**Comment by BenGalewsky** [comment]
I'll show @gordonwatts how to run locally so he can verify directly

**Comment by BenGalewsky** [comment]
@gordonwatts - I think the [README](https://github.com/ssl-hep/ServiceX-DID-finder/blob/rabbit/README.md)  for this branch of DID Finder should tell you how to do this.
There is an argument that lets you run the DID finder with a DID passed in on the command line

Let me know if you find a need for any changes to the README

**Comment by robrwg** [comment]
I attempted to view the README above and got 404. @BenGalewsky can you check?

**Comment by gordonwatts** [comment]
This has been done for a while now - any reason not to close it?
