### ISSUE TITLE
Current rucio did finder swallows several errors

### ISSUE THREAD

**Issue by gordonwatts** [ssl-hep/ServiceX#296]
**Describe the bug**
The rucio did finder has a number of careful checks on its results. In a number of these cases, if an error occurs, it is swallowed. This is a problem in the case that the error is intermittent - and a single file, for example, isn't reported back to the services app.

Spots where this has been spotted:

* In the `ServiceX_Adaptor.py` file - look for the `log.exception` calls for at least two examples.

**Expected behavior**
When running on physics results that require careful accounting, a failure like this needs to trigger a re-start - dropped files are not allowed. When running tests on data, a single missing file isn't needed.

**Additional context**

Given how the DID finder works - takes one message and then explodes it into many - it isn't at all clear how the servicex app should behave in this to cleanly recover (someone who was an expert in microservices - they probably have a pattern for dealing with this).

**Comment by BenGalewsky** [comment]
Probably resolved during DID Finder rearchitecture
