### ISSUE TITLE
ServiceX_App doesn't recognize when its config information is updated in the helm chart with helm upgrade

### ISSUE THREAD

**Issue by gordonwatts** [ssl-hep/ServiceX#297]
**Describe the bug**
If you upgrade your charts values for the ServiceX_App (e.g. change something like the default did finder), and then run `helm upgrade` the command will succeed as expected. However, `ServiceX_App` will not recognize the new values.

**To Reproduce**
1. Run a services chart.
2. Alter a value that is aimed at the `ServiceX_App` flask container
3. Use `helm upgrade` to update the running system
4. Note that the `ServiceX_App` does not restart, and thus does not re-read the settings in the config map that contains these options.

**Expected behavior**
`ServiceX_App` should be aware of the new values, or be forced to restart (thus making it aware).

**Comment by AndrewEckart** [comment]
Manual workaround is probably to `kubectl rollout restart deployment/<release_name>-servicex-app`

It looks like deployments can be tightly coupled to their configmaps so that they will automatically restart when the configmap is altered via `helm upgrade`. See here:
https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments

**Comment by gordonwatts** [comment]
This is still present and bit me today.

**Comment by draghuram** [comment]
I tried to reproduce the problem by changing the value of Rabbitmq retries, as follows:
```
$ helm upgrade --set app.rabbitmq.retries=20 servicex ssl-hep/servicex
```
But I saw that the app Pod restarted and I could see the new value in ``/opt/servicex/app.conf`` inside the Pod. Can you please provide the exact command you used to upgrade? Then,  I will try to reproduce the problem locally and fix it. Thanks.

**Comment by draghuram** [comment]
FYI, I reproduced the problem in my local environment where I changed "objectStore.publicURL" but API server pod didn't restart. I will create PR with a fix soon.
