### ISSUE TITLE
Do not check the hub for transformer image if pull policy is never

### ISSUE THREAD

**Issue by gordonwatts** [ssl-hep/ServiceX#298]
# Story
_As a transformer developer I want to have ServiceX load the transformer image from my local docker image directory so I can quickly iterate building versions of the transformer._

# Assumptions
1. Your local dev machine runs ServiceX

# Acceptance Criteria
1. You can create a new transformer image with a new name/tag, not push it to the hub, and set the pull policy to never for the transformer, and have ServiceX correctly process a transform.

# Currently
* No matter the pull policy ServiceX currently checks docker for the repo - if it isn't there, it fails to go forward with the transform, even if pull policy is never and the image is available locally.
* This might help get ready for the world where all our images are not stored on docker hub.

**Comment by BenGalewsky** [comment]
This can be disabled with ‘app.validateTransformerImage’
