### ISSUE TITLE
Proxy-Exporter should not be baked into the transformer invocation

### ISSUE THREAD

**Issue by gordonwatts** [ssl-hep/ServiceX#299]
# Story
_As a transformer container developer I'd like to develop a transformer that does not need a proxy._

# Assumptions

# Acceptance Criteria
1. Can invoke a new transformer without running `proxy-exporter.sh` as part of the command line

# Current Status

The issue is how we invoke a transformer (from transformer_manager.py in ServiceX_App):

```python
        python_args = ["/servicex/proxy-exporter.sh & sleep 5 && " +
                       "PYTHONPATH=/generated:$PYTHONPATH " +
                       "python /servicex/transformer.py " +
                       " --request-id " + request_id +
                       " --rabbit-uri " + rabbitmq_uri +
                       " --chunks " + str(chunk_size) +
                       " --result-destination " + result_destination +
                       " --result-format " + result_format]
```

SX bakes in the `proxy-exporter.sh` no matter the transformer.

**Comment by BenGalewsky** [comment]
Fixed as part of [ServiceX App PR 126](https://github.com/ssl-hep/ServiceX_App/pull/126)
