### ISSUE TITLE
xCache Support for Rucio DID Finder

### ISSUE THREAD

**Issue by BenGalewsky** [ssl-hep/ServiceX#318]
# Story
_As a ServiceX User I want the DID finder to use xCache so I can efficiently run my queries_

At some point, we lost support for the `--prefix` command line option in the rucio DID Finder. We need this to return replica references that include the local xCache.

# Assumptions
1. Add option back to `values.yaml`
2. Update `runme.sh` to pick this up.

# Acceptance Criteria
1. How will we know when this story is complete

**Comment by oshadura** [comment]
@oshadura: adding myself since I am just interested to follow up an issue

**Comment by oshadura** [comment]
@BenGalewsky do you have any news about this issue?
