### ISSUE TITLE
Deploy Multiple Code Generators into ServiceX Instance

### ISSUE THREAD

**Issue by BenGalewsky** [ssl-hep/ServiceX#339]
# Problem
Multiple code generators need to be deployed by helm to allow a choice of code generator backends.

Part of epic #309 

# Approach
We will explicitly deploy code generators as part of the ServiceX Helm Chart. The initial list of code generators will be:
* Uproot
* ATLAS xAOD
* CMS Run 1
* Python code generator

New endpoint to be added to web service to return the list of supported code generators. This will include a short identifier as well as a longer text description.

These will be configured by the helm chart as a list in the App config file. Entries in this list will include:
1. Short name
2. Long description
3. Internal URL of the code generator

- [ ] Add booleans to enable specific code generators
- [ ] Add property in App config file to related code generators to their in-cluster service URLs
- [ ] Add endpoint to request deployed code generators
- [ ] Add property to transform request to supply the name of the desired code generator
- [ ] Make very clear error message when an invalid code generator is requested
- [ ] Support new property in servicex_frontend

**Comment by BenGalewsky** [comment]
Note --

The new transform request property should be called `code-gen`

The end point to retrieve the list of code generators should be a GET to `/code-generators`

**Comment by gordonwatts** [comment]
@BenGalewsky - we want to deploy two different code generators for ATLAS - one is R21 and the other is R22. Here is the trick - right now they will be the same, though they will need to run different transformers. How can we accomplish that? THe code generator knows what transformer image it should run - so as long as it can communicate that, then this will work.

**Comment by BenGalewsky** [comment]
For this first implementation of multiple code generators we are hardcoding the available code generators in the helm chart and then using boolean flags to determine whether to deploy a specific code generator or not. In future we hope to do this with helm sub charts.

With this structure, I'd be reluctant to add a code generator that is identical just as a way to communicate the default transformer image. The image can be specified in the transform request and so for now I'd prefer that we use that mechanism.

**Comment by gordonwatts** [comment]
I think this is before the discussion we had on slack. As I said there, I'm not totally comfortable with that because we will be making changes to the client software that we will likely have to unmake - so gives the users un-needed churn in their code.

**Comment by gordonwatts** [comment]
Isn't this done and can be closed?

**Comment by BenGalewsky** [comment]
This is done!
