### ISSUE TITLE
Feedback on basic deployment documentation

### ISSUE THREAD

**Issue by zonca** [ssl-hep/ServiceX#349]
I need to deploy ServiceX on a Kubernetes cluster on Jetstream, @BenGalewsky suggested I could use the experience to give some feedback on the deployment docs.
I have experience with Kubernetes but never used ServiceX or Rucio before.

**Comment by zonca** [comment]
It seems the best strategy for me is the basic deployment: https://servicex.readthedocs.io/en/latest/deployment/basic/

it says I need `A valid set of CERN X509 certificates in the ~/.globus directory.`, what is this? I googled but nothing obvious (at least to me) came back. Would you add a link to an explanation on how to get those?

**Comment by BenGalewsky** [comment]
Ah, @zonca - those certs are only required for accessing CERN resources. For our non-authenticated use case you can skip that and in your values.yaml set 
```yaml
noCerts: true
```

Here are the [values](https://github.com/pondd-project/flux-cd/blob/main/servicex/pondd-values.yaml) I used to deploy the PONDD instance on U of Chicago cluster
