### ISSUE TITLE
Spike: Root Cause Analysis of Failed Transformer Jobs

### ISSUE THREAD

**Issue by BenGalewsky** [ssl-hep/ServiceX#36]
# Problem
In processing the 10TB Dataset, we encountered several ROOT files which appear to be corrupt. 

# Approach
Determine if any of these files are corrupt at the source and document a process for requesting corrections.

See if any of the problems are caused by corruption between XCache and the transformer that can simply be corrected by starting over with the file.

See if any of them are caused by corrupted downloads into XCache and if they can be corrected by flushing them from XCache and reloading them.

# Assumptions
This story is best tackled after we have the dead letter queue implemented in #23

**Comment by robrwg** [comment]
@ivukotic can you offer a strategy for how the system should respond to failures to read data from XCache?

**Comment by BenGalewsky** [comment]
Going to close this issue -the new transformer along with the file retry seems to have fixed this!
