### ISSUE TITLE
Rucio DID Finder Returns Logical Filenames with Prefix

### ISSUE THREAD

**Issue by BenGalewsky** [ssl-hep/ServiceX#369]
# Problem
In _coffea-casa_ the xCache is configured to use a "redirector" which does not want the physical file paths, but only needs the logical files.

# Approach
Add an option to the Rucio DID Finder to return logical file paths and skip the `file-replica` lookup.

i.e.

Don't return `root://fax.mwt2.org:1094//pnfs/uchicago.edu/atlaslocalgroupdisk/rucio/user/kchoi/4d/ad/ttHML_80fb_410220_mc16d.root`

instead, returns `user.kchoi:ttHML_80fb_410220_mc16d.root`

**Comment by oshadura** [comment]
Just to show here an example: 
```
[root@cmsaf-servicex-did-finder-rucio-5fc4999547-h9td8 app]# rucio list-files cms:DYJetsToLL_M-50_TuneCP5_13TeV-amcatnloFXFX-pythia8/RunIIAutumn18NanoAODv7-Nano02Apr2020_102X_upgrade2018_realistic_v21_ext2-v1/NANOAODSIM
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+-------------+------------+----------+
| SCOPE:NAME                                                                                                                                                                                               | GUID   | ADLER32     | FILESIZE   | EVENTS   |
|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+-------------+------------+----------|
| cms:/store/mc/RunIIAutumn18NanoAODv7/DYJetsToLL_M-50_TuneCP5_13TeV-amcatnloFXFX-pythia8/NANOAODSIM/Nano02Apr2020_102X_upgrade2018_realistic_v21_ext2-v1/70000/553F8669-95F5-9940-82FE-602AC2423121.root  | (None) | ad:60e81f96 | 426.931 MB |          |
| cms:/store/mc/RunIIAutumn18NanoAODv7/DYJetsToLL_M-50_TuneCP5_13TeV-amcatnloFXFX-pythia8/NANOAODSIM/Nano02Apr2020_102X_upgrade2018_realistic_v21_ext2-v1/130000/244509DB-FF94-9349-BB17-CF7036ABED55.root | (None) | ad:62f9d590 | 1.472 GB   |          |
| cms:/store/mc/RunIIAutumn18NanoAODv7/DYJetsToLL_M-50_TuneCP5_13TeV-amcatnloFXFX-pythia8/NANOAODSIM/Nano02Apr2020_102X_upgrade2018_realistic_v21_ext2-v1/130000/5F5C3284-CB57-4D47-8BC5-70391D5B6851.root | (None) | ad:381dbaa2 | 1.389 GB   |          |
| cms:/store/mc/RunIIAutumn18NanoAODv7/DYJetsToLL_M-50_TuneCP5_13TeV-amcatnloFXFX-pythia8/NANOAODSIM/Nano02Apr2020_102X_upgrade2018_realistic_v21_ext2-v1/130000/8504F24A-6279-7C44-908C-97766BB045BC.root | (None) | ad:57304e22 | 59.598 MB  |          |
| cms:/store/mc/RunIIAutumn18NanoAODv7/DYJetsToLL_M-50_TuneCP5_13TeV-amcatnloFXFX-pythia8/NANOAODSIM/Nano02Apr2020_102X_upgrade2018_realistic_v21_ext2-v1/260000/26DFECED-BB57-0942-96D5-8A44002930C4.root | (None) | ad:22deba82 | 963.791 MB |
```

**Comment by oshadura** [comment]
So for CMS and ATLAS case it will be ideal to have returned: 
`/store/mc/RunIIAutumn18NanoAODv7/DYJetsToLL_M-50_TuneCP5_13TeV-amcatnloFXFX-pythia8/NANOAODSIM/Nano02Apr2020_102X_upgrade2018_realistic_v21_ext2-v1/70000/553F8669-95F5-9940-82FE-602AC2423121.root`. Then in the CMS case we could prepend `root://xcache/` or `root://<redirector name>/` and for the ATLAS case it could be prepended`root://<xcache host>//root://<redirector host>/`.

**Comment by oshadura** [comment]
Hi Ben, I tested and still doesn't work, I get in logs:
`Transform 46229d47-6b75-4bc1-a5b7-cab60651df4f had 966 errors:
  Error transforming file: red-xcache1.unl.educms:/store/mc/RunIIAutumn18NanoAODv7/DYJetsToLL_M-50_TuneCP5_13TeV-amcatnloFXFX-pythia8/NANOAODSIM/Nano02Apr2020_102X_upgrade2018_realistic_v21_ext2-v1/120000/D92E1746-01C8-4D4E-96F0-39FEBC355CB6.root`
It looks like we are just prepending to xcache value `red-xcache1.unl.edu` to logic file `cms:/store/mc/RunIIAutumn18NanoAODv7/DYJetsToLL_M-50_TuneCP5_13TeV-amcatnloFXFX-pythia8/NANOAODSIM/Nano02Apr2020_102X_upgrade2018_realistic_v21_ext2-v1/120000/D92E1746-01C8-4D4E-96F0-39FEBC355CB6.root` ---> instead I need `root://red-xcache1.unl.edu/` be prepended to `/store/mc/RunIIAutumn18NanoAODv7/DYJetsToLL_M-50_TuneCP5_13TeV-amcatnloFXFX-pythia8/NANOAODSIM/Nano02Apr2020_102X_upgrade2018_realistic_v21_ext2-v1/120000/D92E1746-01C8-4D4E-96F0-39FEBC355CB6.root`
