### ISSUE TITLE
Elastic Search Logging of Events and Errors

### ISSUE THREAD

**Issue by BenGalewsky** [ssl-hep/ServiceX#37]
# Story
_As a ServiceX Administrator I want to be able to view and analyze events and error reports from the ServiceX transformers so I manage my system_

# Assumptions
1. All events and error reports go to Elastic Search instance
2. Elastic Search is optional to a ServiceX deployment
3. Events are presented as JSON docs

# Acceptance Criteria
1. Transform Start messages are logged to ES with timestamps
2. Transform complete events logged to ES
3. Transform exceptions are logged to ES
4. Ability to generate basic graphs and reports using Kabana

**Comment by ivukotic** [comment]
We use Kibana, not Grafana. Also if you are sending messages like "1000 events processed" and not "requestId had 1123000 events processed", you will need to write ingress pipeline to aggregate messages.

**Comment by BenGalewsky** [comment]
The flask server aggregates the number of events processed, but only at the end of each file - do you think that would be sufficient?

**Comment by ivukotic** [comment]
You’ll still need something to aggregate over request.

**Comment by BenGalewsky** [comment]
I updated the acceptance criteria to drop support for the intermediate updates from the transformer. We now get the total number of events after each file. This keeps the traffic to the REST server lower so we can focus on the end-to-end status reporting.

If we decide we need to log more frequent updates from the transformer then we can think through a higher-volume solution

**Comment by ivukotic** [comment]
I am not sure how you will handle it, but transitions should be added to "info" field of the request and paths. In case of paths that can be <timestamp> starting in pod:[pod name], <timestamp> error: xxx, retrying, <timestamp> starting attempt 2 in [pod name], ... <timestamp> finishing.
