### ISSUE TITLE
My private Minio

### ISSUE THREAD

**Issue by ivukotic** [ssl-hep/ServiceX#371]
# Story
As a prolific analyzer, I want to have my own private Minio where only results of my requests will be stored.
Ideally it would be a self cleaning  simple helm chart with a very simple configuration that looks something like this:
{
"servicex instance": "xaod.af.uchicago.edu",
"users": ['Peter', 'Joe'],
"minio":
  "storage class": "MyObjectStorage"
  "user": "xxx"
  "pass": "yyy"
  "address": "zzz"
} 

# Acceptance Criteria
When there is a chart providing the functionality.

**Comment by sthapa** [comment]
This has been implemented and merged.
