### ISSUE TITLE
Too many ServiceXes

### ISSUE THREAD

**Issue by ivukotic** [ssl-hep/ServiceX#372]
# Story
As a user, I would prefer to have one place to create account and login in to, one place to submit my requests too, one dashboard that will show all of my requests. 
I would also like very much if my requests would use all the possible resources independently where they are.

Multiple ServiceXes complicate things for me as I have no way of: 
a) discovering different ServiceX instances
b) knowing what are resources behind them
c) how close are they to my data (and I don't know all the places my data are at)
d) know how reliable or busy at the moment different ServiceXes are. 
e) know if different ServiceXes are running all the latest code. 

# Acceptance Criteria
User is blissfully unaware of any infrastructure details but requests are processed lightning fast.

**Comment by gordonwatts** [comment]
I am removing myself from this. I believe the code generators is a step towards solve this - and we can come back and re-evaluate this when that is working. So I'm going to close this for now.
