### ISSUE TITLE
Downloadable flat ROOT File

### ISSUE THREAD

**Issue by BenGalewsky** [ssl-hep/ServiceX#39]
# Story
_As an analyzer I want to be able to download a flat ROOT File for my request so I can continue my analysis with familiar tools_

# Assumptions
1. Based on story #34 which has all of the machinery for the object store and generating downloadable files

# Acceptance Criteria
1. Given I have submitted a request and the request specifies a ROOT file as the result When I run the transform then I should be able to download a ROOT File and verify that it can be opened and inspected with uproot

**Comment by kyungeonchoi** [comment]
@BenGalewsky - have we implemented this feature somewhere? Sorry if I miss something!
