### ISSUE TITLE
Explicitly Manage Python Dependencies

### ISSUE THREAD

**Issue by sthapa** [ssl-hep/ServiceX#390]
We've had two instances in the last 2 weeks or so where a release broke because an underlying python module was updated and that caused problems.  We need to pin dependencies or have a mechanism for doing so without letting modules get too stale.

**Comment by sthapa** [comment]
One approach would be to use something pipenv lock  to lock down our modules and transitive dependencies and then something like https://pyup.io/ or https://requires.io/ to notify us of dependency updates.  Although that helps, we'd still need to test any dependency before updating our requirements.

**Comment by BenGalewsky** [comment]
Over in funcX, we use a file called `requirements.txt.in` which contains unpinned, top level requirements. We have a Makefile that basically saves the output of `pip freeze` into `requirements.txt`

The intention is that we periodically update the pinned dependencies

```shell
.PHONY: freezedeps
freezedeps:
	echo "# frozen requirements; generate with 'make freezedeps'" > requirements.txt
	tox -qq -e freezedeps | tee frozen-requirements-tree.txt
	sed 's/ //g' frozen-requirements-tree.txt | sort -u >> requirements.txt
```

**Comment by gordonwatts** [comment]
This is a nice idea. And if you need to, you can probably pin the dependencies in requirements.txt.in (not knowing what the `tox` command is).

**Comment by BenGalewsky** [comment]
_As a ServiceX developer I want to explicitly manage when python dependencies are updated so I can confidently rebuild the service_

We want to have a better process for pinning dependencies and then updating those pins when we want to bring in recent versions of our dependent libraries.

There are a few technologies out there for this. Review a couple of them, suggest a solution and update our services to use it.

# Assumptions
1. We want a lock file to pin all of the dependencies in `develop` branch
2. We want an easy way to update all of the libraries, test, and update the lock
3. It needs to work well inside the docker build
4. It needs to support the `safety` check to flag known vulnerabilities
