### ISSUE TITLE
Bad dcache server causes same file to be rendered multiple times

### ISSUE THREAD

**Issue by gordonwatts** [ssl-hep/ServiceX#413]
While running a transform, a GRID file was unavailable. It caused a hang (the hang would have gone on forever). When they fixed it (cause was a dcache server at the GRID site, nothing to do with ServiceX), ServiceX picked up working - but seems to have processed the same file three times.

![image](https://user-images.githubusercontent.com/1778366/172951900-d0d3a10d-90e8-4df3-be88-42d55f4a7b2e.png)

**To Reproduce**
1. Submit transform on file that will hang (not crash!)
2. "restart" the file streaming

This particular error happened on the AF xAOD server under the `gwatts` account: aa422a89-b76d-4d84-b65d-314cea26c544

**Expected behavior**
Either the transform should have failed, or only 2 files should have been run.

**Comment by fengpinghu** [comment]
[serviceapp.log](https://github.com/ssl-hep/ServiceX/files/8880036/serviceapp.log)
servicex app logs related to this transform request(kubectl logs -n servicex-xaod xaod-servicex-app-5bf46f74dd-cdlsl | grep transformer-42899670-dce4-4115-9c9e-769fc0e05594)

**Comment by gordonwatts** [comment]
Looking at that log file it looks like multiple transformers got ahold of the file. Is there a race condition when things fail?

**Comment by gordonwatts** [comment]
I wonder if this is one of the cases that triggers #460?

**Comment by ponyisi** [comment]
I expect this is addressed now.
