### ISSUE TITLE
Kafka on River Cluster

### ISSUE THREAD

**Issue by BenGalewsky** [ssl-hep/ServiceX#42]
# Problem 
Currently we are only running Kafka on the GKE cluster. We need to make sure it can easily and reproducibly be deployed on SSL infrastructure.

# Assumptions
1. Make use of `local-volumes` storage class
2. Deploy three brokers
3. Add DNS entries to `slateci.net`
4. Deploy Kafka manager dashboard too

# Acceptance Criteria
1. Deploy Kafka to river from helm chart with values.yaml
2. Log into Kafka manager dashboard
3. Use Kafka shell script to create topic, publish a message and consume
4. Documentation in Markdown in ServiceX repo

**Comment by robrwg** [comment]
Can this please be updated?

**Comment by mfrdrcks** [comment]
Kafka is deployed on River using helm chart with values.yaml.
Kafka shell scripts can be used to create topics, publish messages, and consume messages, as long as the shell scripts are run on River.
Attempting to verify the IPs that should be used and that those IPs are correctly accepting incoming traffic from outside River (known that the IPs currently being advertised do not correctly accept incoming traffic).
Have not tested the Kafka manager dashboard.
Have not documented the deployment.

**Comment by robrwg** [comment]
I think it is important that we can reliably deploy all of the components of ServiceX.  This looks like its not quite there.

**Comment by BenGalewsky** [comment]
Looks like we are splitting this story in two. This one will now end with Kafka deployed on River and accessible inside the cluster. Since we don't want to allow for unsecured remote access, we now have story #72 to add certs to the deployment to control access

**Comment by mfrdrcks** [comment]
This is not quite there. While this now works to allow remote Kafka connections, it does not require authentication, which will be a requirement on many systems. I am working on securing Kafka, testing the manager dashboard, and documenting the deployment.

**Comment by robrwg** [comment]
hi @mfrdrcks can you first concentrate on the case Ben describes, i.e. deployed Kafka services allowing for local access only? Perhaps thats already in the bag?

**Comment by robrwg** [comment]
should Kafka be listed to the list on the main readme? https://github.com/ssl-hep/ServiceX   (note all of the other services seem to be listed/described; notably absent is Kafka)

**Comment by mfrdrcks** [comment]
Kafka is already working locally. I have the documentation in this readme about how to deploy it (with remote access even, though not with authentication). I am checking with Ben about the management dashboard. I didn't see one with the helm chart, and there are a few options available. If we split out authentication, then this should just be minor tweaks and ready.

As for including this in the main readme, Kafka isn't included in the main ServiceX Helm chart. I'm not certain where the line is drawn without further digging, but it may be intended to include it after we have the kinks worked out here. At that point it would make sense to include it in the main readme, but while not in the Helm chart included there, Kafka doesn't make sense to add to the documentation.

**Comment by robrwg** [comment]
@BenGalewsky I think we have two versions - perhaps we compare @mfrdrcks and @ivukotic Kafka deployments side-by-side?
