### ISSUE TITLE
Jupyter Notebook to Demo Z-Peak Analysis

### ISSUE THREAD

**Issue by BenGalewsky** [ssl-hep/ServiceX#45]

**Comment by BenGalewsky** [comment]
Basic notebook done in examples directory of the v0.1-prep branch. This submits a transform request, shows how you can request the current status.

There are two notebooks in the directory - one interacts with Minio so you can just download a parquet file, load it with pyArrow and get to work. The other connects to Kafka and streams awkward arrays.

Still need the calculations and plots to complete
Assigning to @mweinberg2718

**Comment by robrwg** [comment]
Where are the instructions?

**Comment by mweinberg2718** [comment]
Instructions can be found in ServiceX repo README.md. Branch with current notebook is v0.1-prep:

https://github.com/ssl-hep/ServiceX/tree/v0.1-prep

**Comment by robrwg** [comment]
What remains to be done with this notebook?

**Comment by BenGalewsky** [comment]
This has be superseded by the various example codes and now the google colab notebook that works with _coffea_
