### ISSUE TITLE
GitHub Action To Release Helm Chart

### ISSUE THREAD

**Issue by BenGalewsky** [ssl-hep/ServiceX#458]
_As a ServiceX developer I want a GitHub action to publish the helm chart so I can easily and reliably make a release of the system_

## Assumptions
1. Will be triggered with the _Publish Release_ action
2. The action will:
  a. Tag the develop branch with the release name
  b. Update the `appVersion` and chart version to the release name
  c. Update `values.yaml` so each of the tags points to images tagged with the release name
  d. Package up the helm chart
  e. Re-index the ssl-helm chart repo
  f. Publish the chart
  g. Update the integration test deployments in `flux-river-configs` repo to pull the newly published chart
3. The updated values and Chart.yaml versions will not be checked back into the repo. They will be modified in the GHA VM, published in the helm chart and then deleted.

These two files must be updated for the flux process to update the integration test deployments on river
* [servicex-int-uproot/values.yaml](https://github.com/ssl-hep/flux_river_configs/blob/79aa8cf7506d1c66cde44dc12ecefec7f584620c/servicex-int-uproot/values.yaml#L16)
* [servicex-int-xaod/values.yaml](https://github.com/ssl-hep/flux_river_configs/blob/79aa8cf7506d1c66cde44dc12ecefec7f584620c/servicex-int-xaod/values.yaml#L16)

## Acceptance Critera
Given the builds on `develop` branch are successful, when I _Publish a Relase_ through the GitHub UI with a version label then the chart will be built for that version, published to ssl-helm-charts and deployed to the integration test deployments on river.

**Comment by BenGalewsky** [comment]
@sthapa has suggested using [pyYaml](https://pyyaml.org/wiki/PyYAMLDocumentation) for updating the tags instead of sed

**Comment by BenGalewsky** [comment]
@gordonwatts suggested that we check docker hub to validate that the images are all published

**Comment by sthapa** [comment]
Using a python script and pyyaml to load and modify the images will avoid issues down the road.  We've already gotten bitten by the sed script updating the wrong tag fields.  Also, updating another repo and committing changes has some tricky use cases.  If the other repo gets updated while the changes are being made, you'll need to be able to handle out of date repos and/or merge conflicts in the action.
