### ISSUE TITLE
Retry ROOT files on Failure

### ISSUE THREAD

**Issue by BenGalewsky** [ssl-hep/ServiceX#46]
- [ ] Remove `xcache` and try again
- [ ] Keep track of last event sent to Kafka
- [ ] Improve reporting of root cause of failure

**Comment by mweinberg2718** [comment]
Pseudocode:

While not done:
    If retries <= 2
        Try:
            Transform file
            done
        Except:
            retries += 1
    else
        Put in DL queue
        done
