### ISSUE TITLE
DID Finder For CMS

### ISSUE THREAD

**Issue by BenGalewsky** [ssl-hep/ServiceX#48]
_As a CMS analyzer I want to be able to transform CMS datasets so I can produce results_

# Assumptions
1. This will connect to the CMS Rucio Server
2. It will require an X509 proxy that works with the CMS virtual org

# Acceptance Criteria
1. Given I have CMS credentials and a transform that references a CMS DID When I submit the request Then the DID finder should report all of the Root files associated with that DID

**Comment by robrwg** [comment]
Should this be "DID Finder *for* CMS"?

**Comment by BenGalewsky** [comment]
Closing this as duplicate of #97
