### ISSUE TITLE
Provide paths to files

### ISSUE THREAD

**Issue by BenGalewsky** [ssl-hep/ServiceX#5]
# Story
_As an analyzer I want to paths to local cached files so I can begin transformation _

# Acceptance Criteria
1. Scheduler picks next file to process

# Assumptions
1. Files served out of xCache
2. Files prefetched into Xcache using external command line tools
3. Only need one file at a time

**Comment by ivukotic** [comment]
creating docker image for this pod. based on rucio-client. for now will use my rucio account. later we will have to go with user's proxy or service acc.

**Comment by ivukotic** [comment]
request is now prescreened: files and paths are being looked up in Rucio and stored in ES for further processing.
