### ISSUE TITLE
Generate ServiceX Users by Command

### ISSUE THREAD

**Issue by BenGalewsky** [ssl-hep/ServiceX#501]
_As a ServiceX Admin I want to be able to explicitly create users so I can automate onboarding of new users_

# Assumptions
1. This will be implemented as a [flask CLI plugin](https://flask.palletsprojects.com/en/2.2.x/cli/#plugins)
2. The CLI can add a user along with a pre-existing token. This is useful for the integration testing CI runner since the token remains valid even after a database wipe.
3. We retain GlobusAuth. This feature will allow admins to pre-approve users. They will authenticate with GlobusAuth, but if their record already exists in the DB their token will be added and immediately be granted access.
5. The helm chart will allow admins to specify a cluster secret. This should contain a CSV file of initial users to create along with an optional pre-existing token. Upon startup, the app will attempt to create these users. It will need gracefully handle the users already being in the db since there can be multiple instances of the app running in the cluster 
6. The serviceX cli will be extended to add a command to add users
    1. It will launch a task in cluster with the app image and the new `flask add-user` command
    2.

**Comment by BenGalewsky** [comment]
From @hollowec
>I am looking for a way to pre-configure users in our ServiceX deployment (configured with globus auth setup), so they do not need to use a browser to login and create a profile manually, and wait for approval before using the system. The idea would be to pre-populate a local user's ~/sevicex.yaml file when their local UNIX account is created. I can get a user's sub id with globus get-identities (if they've already used globus), and populating the fields in the ServiceX users table in postgresql is straightforward, except I cannot find a way as the admin user to generate a refresh token for another user using the REST API: this would be a useful feature if it's possible to implement.

**Comment by BenGalewsky** [comment]
I can't imagine any way to generate a token without the user providing their credentials. It could be that the user can be created, they would still have to go to the web UI and generate their token, but they don't need to await approval...

**Comment by BenGalewsky** [comment]
Is the answer to this to bypass external auth providers? i.e. we would generate our own JWT - users could only be created by the admin via this command line tool

**Comment by hollowec** [comment]
Hi @BenGalewsky, thanks for looking into this.  I had also created this issue here: https://github.com/ssl-hep/ServiceX_App/issues/182 .  Should we close that one?

**Comment by BenGalewsky** [comment]
> Hi @BenGalewsky, thanks for looking into this. I had also created this issue here: [ssl-hep/ServiceX_App#182](https://github.com/ssl-hep/ServiceX_App/issues/182) . Should we close that one?

That repo was archived when we migrated to the monorepo, so issues there can't be updated/closed anymore

**Comment by hollowec** [comment]
@BenGalewsky ok thanks for the info about the original issue and the repo.  Yes, I think giving the option to bypass external auth providers, where all users would have to be created by the admin would work for us.  ServiceX is only available within our network currently.  The plan is for federated users at our facility to only have access to the system from within Jupyter, so they will not be able to use a browser to access the web UI.
