### ISSUE TITLE
ServiceX DID-finder stalls for Rucio dataset accessed via https protocol

### ISSUE THREAD

**Issue by kyungeonchoi** [ssl-hep/ServiceX#539]
**Describe the bug**
ServiceX DID-finder stalls for Rucio dataset accessed via https protocol. A ServiceX request seems to wait for the file list returned from DID-finder. Once Rucio dataset is moved to MWT2 (xrood protocol) ServiceX can get the file list and runs fine. 

An example Rucio RSE for https protocol: 
`NEVIS_GRIDFTP: https://xenia.nevis.columbia.edu:1094/atlas/dq2/rucio/user/dpanchal/be/a4/user.dpanchal.31107845._000054.hist-output.root`

**Comment by ivukotic** [comment]
Well, I would not call it a bug... All of the ATLAS storages are required to provide an xroot endpoint. So this is an issue of the Nevis storage. On the other hand we would like to be able to use (and also cache) data read over http. I am working on it, and if/when performance is good enough, I will make it possible to use both xroot and http.

**Comment by ponyisi** [comment]
Hi Ilija - understood that it's an issue with Nevis not necessarily supporting the "proper" endpoint, but I consider it a problem if we cannot access a file that is available via "rucio get" (as this one is). KyungEon, you reported a site that was webdav ?

**Comment by kyungeonchoi** [comment]
Thanks @ivukotic for looking into this problem. I didn't know that http doesn't need to be a supported endpoint. As you said it would be still good to support both xrootd and http.
@ponyisi - I will talk to Dev.

**Comment by ivukotic** [comment]
Hi,

I just started work on getting xcaches to be able to use paths like root://xcache.xx.edu//http://origin.xx.edu/…

Ilija
