### ISSUE TITLE
xAOD Transformer Writes Parquet

### ISSUE THREAD

**Issue by BenGalewsky** [ssl-hep/ServiceX#549]
We need the transformer sidecar to notice when the user has requested parquet output, but the transformer's capabilities.json shows that transformer doesn't support that format.

The conversion from root to parquet will be done in the sidecar. 

We will need some physics help to write a function to use uproot to read the output from the xAOD transformer and write a parquet file.

**Comment by gordonwatts** [comment]
I hope `python` is ok - I have no idea how to do it in C++!

```python
import uproot
import awkward as ak

with uproot.open(file) as data:
    all_data = data['treeme'].arrays(library='ak')
    ak.to_parquet(all_data, "output.parquet")
```

And then reading it back:

```python
new_data = ak.from_parquet("output.parquet")
new_data['JetPt']
```

YMMV - in particular, the `treeme` output tree name. You might need to use `data.keys()` and then grab the key from there. That would be the most flexible. To make it safe you should probably grab every key you find - as at some point these root files may contain multiple trees.
