### ISSUE TITLE
Service to Distribute X509 Proxy

### ISSUE THREAD

**Issue by BenGalewsky** [ssl-hep/ServiceX#57]
# Story
_As an analyzer I want the service to use a proxy for a service X509 cert so the components can access experiment resources_

# Assumptions
1. Service account credentials and keys deployed as part of helm chart
2. A new service will be created to generate the proxy and update a common secret

# Acceptance Criteria
1. Given I have deployed ServiceX with an Atlas user credentials the following services should be able to access ATLAS:
- DID Finder
- Preflight Check
- Transformer

**Comment by robrwg** [comment]
How was this ultimately completed?

**Comment by BenGalewsky** [comment]
@robrwg - see PR #64 it has complete documentation on the approach taken and the commit history of the exact code changes required to implement the functionality.
