### ISSUE TITLE
Secure access to REST Endpoint

### ISSUE THREAD

**Issue by BenGalewsky** [ssl-hep/ServiceX#61]
# Story
_As an analyzer I want to securely connect to ServiceX so I can make use of the resources_

# Assumptions
1. Will use a globus auth JWT
2. We'll have a valid user database to whitelist specific users
3. We'll need some sort of user interface to approve users that come along and request access
4. The non-user facing endpoints are not exposed via ingress controller
5. The user facing endpoints are exposed via ingress controller
6. New endpoint for accessing my user record

# Acceptance Criteria
1. Given I have a valid GlobusAuth token and I have been granted access to the system when I submit a transform request Then it should be accepted
2. Given I have an invalid Globus Auth token when I submit a transform request then it should be rejected
3. Given I have not been granted access to the service and I have a valid token when I submit a transform request it will be rejected 
4. Given I have a valid token and I've been granted access to the service When I attempt to connect any of the non-user facing endpoints then I should receive an error
5. Given I have a valid token when I access /user endpoint then I receive a JSON document describing my user record

**Comment by gordonwatts** [comment]
- Could we add an option that we can turn this on and off in the helm chart? This is, obviously, important for testing.
- Will this work prevent me from running something at UW? We do not use, obs, the same permissions and ID system as UChicago.

**Comment by robrwg** [comment]
I think its a mistake to have this project weighed down by the myriad of campus identity management systems out there and having the full system deployable on everyone's laptop.  (On another project we are attempting to prepare for different campus LDAPs, and its a huge chunk of effort.)  

Perhaps this story needs to be re-scoped.

**Comment by cnweaver** [comment]
Globus interoperates with many campus SSO systems, so a single system should be able to work with both U. Chicago and U. Washington credentials.

**Comment by robrwg** [comment]
right - CILogon, which UW supports.  I'm not sure what Gordon wants to be able to do, though.

**Comment by gordonwatts** [comment]
The general theme: the Campus authentication scheme should not be baked in - is I think important. This will run in Europe and well as here, and given how authentication is going to change... I also want to be able to run this, for example, on a firewalled cluster here at UW - if you are through the firewall, then you get access. Hooking into the campus system is a big job - I suspect reviews are involved. So, I'd like a light weight way around this.

If the auth module is "plug-in" then you could use a campus system, or some simple checks, or turn it off totally.
