### ISSUE TITLE
Example notebook dependencies fail to install

### ISSUE THREAD

**Issue by cnweaver** [ssl-hep/ServiceX#63]
Using the current master, attempting to run the demo notebook currently fails due to an issue with installing its dependencies. 

Expected behavior: Following the demo instructions should succeed without errors. 

Observed behavior: 
`pip` fails with an error while processing the notebook's requirements.txt:
```
$ virtualenv servicex_demo
New python executable in /Users/admin/Work/Chicago/ServiceX/servicex_demo/bin/python
Installing setuptools, pip, wheel...
done.
$ cd servicex_demo/
$ . bin/activate
$ pip install -r ../ServiceX/examples/requirements.txt
ERROR: Could not find a version that satisfies the requirement matplotlib>=3 (from coffea>=0.5.6->-r ../ServiceX/examples/requirements.txt (line 10)) (from versions: 0.86, 0.86.1, 0.86.2, 0.91.0, 0.91.1, 1.0.1, 1.1.0, 1.1.1, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1rc1, 1.4.1, 1.4.2, 1.4.3, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 2.0.0b1, 2.0.0b2, 2.0.0b3, 2.0.0b4, 2.0.0rc1, 2.0.0rc2, 2.0.0, 2.0.1, 2.0.2, 2.1.0rc1, 2.1.0, 2.1.1, 2.1.2, 2.2.0rc1, 2.2.0, 2.2.2, 2.2.3, 2.2.4)
ERROR: No matching distribution found for matplotlib>=3 (from coffea>=0.5.6->-r ../ServiceX/examples/requirements.txt (line 10))
```

**Comment by cnweaver** [comment]
This turns out to be due to an unstated requirement of python 3, as Matplotlib 3 is not available for python 2.7.

**Comment by robrwg** [comment]
Marc - comment?

**Comment by robrwg** [comment]
I cannot find the example notebook instructions.

**Comment by mweinberg2718** [comment]
After discussion with @cnweaver, added a note for the user to run this in a Python 3 notebook (https://github.com/ssl-hep/ServiceX/tree/v0.1-prep).
