### ISSUE TITLE
Web dashboard of the new dataset_manager release

### ISSUE THREAD

**Issue by kyungeonchoi** [ssl-hep/ServiceX#681]
**Describe the bug**
- "Files completed" is NOT automatically updating (2 in the screenshot)
- "Workers" NOT showing up (3 in the screenshot)

**To Reproduce**
Submit transform request at testing-4 instance (as of Jan 9) and check web dashboard

**Screenshots**
![dashboard](https://github.com/ssl-hep/ServiceX/assets/54450665/9d658ee7-efda-46e6-a71f-776a1b826c87)

**Comment by ivukotic** [comment]
I just fixed it and merged into develop branch
