### ISSUE TITLE
Web dashboard - selection string rendering for Python transformer

### ISSUE THREAD

**Issue by kyungeonchoi** [ssl-hep/ServiceX#682]
**Describe the bug**
Selection shown in the web dashboard is non human-readable base64 encoding (shown in the screenshot). It often becomes very long and doesn't wrap line, which causes no access to other information (such as title, request ID) due to limited horizontal scrolling.

**Expected behavior**
- Render user provided python function properly
- Properly show other information

**Screenshots**
<img width="1676" alt="dashboard_transformation" src="https://github.com/ssl-hep/ServiceX/assets/54450665/55fcf06d-3964-47f0-9486-b005436b56c6">

**Comment by ivukotic** [comment]
I don't see this issue? 
![image](https://github.com/ssl-hep/ServiceX/assets/1736984/5f242871-826a-4976-b81e-eae4c15e0181)

**Comment by kyungeonchoi** [comment]
Yeah, it's only for Python transformer
