### ISSUE TITLE
Request document included in object-store bucket

### ISSUE THREAD

**Issue by BenGalewsky** [ssl-hep/ServiceX#70]
# Story
_As an analyzer I want to be able to see the transform request that generated the files in an object store so I can maintain the provenance of the files_

# Assumptions
1. Just store the JSON document from the original request in the object-store
2. This can be done in the app [when it creates the bucket](https://github.com/ssl-hep/ServiceX_App/blob/096c90a7cae5a0c93522d4491cb3d36cdb3bd5d5/servicex/resources/submit_transformation_request.py#L111) prior to launching transformers

# Acceptance Criteria
1. Given I have submitted a transform request and the request has object-store as the destination When I look inside the resulting bucket Then I should see an object called `request.json` and it should contain the original request document

**Comment by gordonwatts** [comment]
This might be obsolete at this point!
