### ISSUE TITLE
Multiple Trees in a Request

### ISSUE THREAD

**Issue by BenGalewsky** [ssl-hep/ServiceX#71]
# Story
_As an analyzer I want to be able to transform multiple trees in a single request so I can efficiently extract the data I need for my analysis_

# Assumptions
1. Only works for object-store destination
2. Each tree winds up in its own set of files since the events won't line up post-selection
3. The file names describe the tree
4. The `tree` property in the request can be "*" or a coma separated list of trees
5. The transformer reads the file only once

# Acceptance Criteria
1. Given I submit a transform request with "*" as the tree property When the transform is complete Then I should see output files for each input file and each tree
2. Given I submit a transform request with a coma separated list of trees as the tree property When the transform is complete Then I should see output files for each input file and each requested tree

**Comment by gordonwatts** [comment]
Why should this only work for the object store?

**Comment by BenGalewsky** [comment]
The output from the transformer will be one flat root file per tree. At this point I don't want to think about how that fan-out would be represented in Kafka. I'm sure we can come up with something, but let's start with the simpler case for now since that is how @kyungeonchoi will be using it to start with.

**Comment by gordonwatts** [comment]
Ok - I clearly do not understand the format of these root files - @kyungeonchoi - how are these files laid out? What do the many tree's represent?

**Comment by kyungeonchoi** [comment]
@gordonwatts, I would say this is a typical ntuple with multiple trees for systematic variations.

**Comment by ponyisi** [comment]
I would like to make a concrete strawman proposal for how to handle this in a minimally-invasive way.

- client libraries generate qastle that give the names of the trees to be processed
- the python module dumped by the uproot code generator gets an additional function list_of_trees() which returns a list of tree names
- the uproot transformer "shell" calls run_query once for each tree in the list of trees, passing the name as an argument

We could optimize this a bit (e.g. the generated code's default run_query could return a generator of (treename, array) pairs, or a dict if there are no memory issues.

**Comment by masonproffitt** [comment]
I have a strong preference for `run_query` (which is generated directly by `func-adl-uproot`) to only ever return `ak.Array`s. Awkward Array supports nested records, though, so it's not hard to bundle results from multiple trees into one `Array`.

One issue here is that it may not be optimal to run on all trees in one process. If there are hundreds of trees, it could be better to run them in separate workers, which I assume would require the tree name to be propagated up to the same level as the file handling.

**Comment by ponyisi** [comment]
@masonproffitt - I would not want to bundle the results from multiple trees into a giant Array; this sounds to me like it would add potentially significant complexity for no real benefit. If you prefer run_query can default to only running on the "first" array, and we'll have the surrounding transformer code manage looping over the query trees.

I think the second question (whether to run all trees in one process) is not an optimization for us to worry about at this time. If the user wants to distribute queries over multiple workers, for now they can control this via the queries they issue.

**Comment by masonproffitt** [comment]
It's not a default per se; `run_query` does not accept lists of tree names (only strings), and there's no reason to change that unless it's going to return all tree results at once. Returning a single `Array` wouldn't be any more complex than returning a `dict` (as long as there are no memory issues, as you mentioned). But otherwise, yeah the only reasonable way to handle this then is to have the transformer loop through and run `run_query` on each tree.

**Comment by ponyisi** [comment]
By "default" I meant "when you do not explicitly pass a tree name argument". You could make that argument mandatory of course...

**Comment by gordonwatts** [comment]
For returns then, what if you get a dictionary coming back. One dictionary entry per tree. And then you'd get a list of URL's for that tree.

This info, @BenGalewsky , would need to be encoded in the file names in the bucket - so you could scan all the files in the bucket, and then build the key:value list. That sound reasonable?

**Comment by ponyisi** [comment]
@gordonwatts could you elaborate - what do you mean by "returns" here? As mentioned earlier I do not think this needs to be supported for return file types that cannot store all the trees in a single file (i.e. parquet). In this model there is no reason at all to change the return file semantics.

**Comment by gordonwatts** [comment]
The way the transformer runs it naturally generates a file per tree. So, if we put at the top level the loop over multiple trees, then naturally you get multiple files, one per tree.

I'm going for a returned dictionary, where the key is the tree name.

I'm also warming to this when it comes to dealing with systematic errors. So you get back a dictionary with an entry per sys variation.

And finally, if you specify only one tree, `"tree-name"` you get back just the files, no dictionary, and if you specify `["tree-name"]` you'd get back a dictionary with one entry.

**Comment by ponyisi** [comment]
Hi @gordonwatts ,

*Please* let's coordinate on what you're implementing. There is IMO no reason at all to generate 50 small ROOT files instead of one large ROOT file, and no reason to run the transformer 50 times per input file. KyungEon has done a (hard-wired) implementation that generates one output ROOT file per input file; there is nothing preventing the transformers from operating like this.

It is true that the way the *generated Python code* runs, it naturally generates one array per input tree, but the way this is packaged into a file is absolutely up to us. ServiceX already has a real problem with producing too many small outputs and exploding this number is not going to help.

**Comment by gordonwatts** [comment]
Sure! No work has started yet.

How do we deal with parquet files - which are supposed to be equivalent?

**Comment by masonproffitt** [comment]
One note here: Awkward has no problem storing multiple `Array`s in a single Parquet file. For example, `ak.to_parquet(ak.Record({'tree1': array1, 'tree2': array2, ...}), 'new_file.parquet')` just works. I have no idea how efficient it is for reading/writing in terms of time, memory, CPU, disk space, file layout, etc., but I've tested the roundtrip back to Awkward `Array`s and see no issues with the functionality itself.

**Comment by gordonwatts** [comment]
Ah, fantastic, thank you!

**Comment by ponyisi** [comment]
Implemented for uproot-raw; possibility exists for other codegens.
