### ISSUE TITLE
multiple parameters Selection Examples

### ISSUE THREAD

**Issue by zhonglol** [ssl-hep/ServiceX#713]
**Describe the bug**
I was trying to using ServiceX to select multiple parameters, and I followed up with this example, (https://github.com/ssl-hep/ServiceX/blob/bdb0e4827f19a8426637ffe0c994371184b729ec/examples/ATLAS/Z_ee.py#L12-L14), but the code seems like not work. 

**To Reproduce**

from func_adl_servicex import ServiceXSourceXAOD

query = "(call ResultTTree (call Select (call SelectMany (call EventDataset (list 'localds:bogus')) (lambda (list e) (call (attr e 'Jets') 'AntiKt4EMTopoJets'))) (lambda (list j) (/ (call (attr j 'pt')) 1000.0))) (list 'JetPt') 'analysis' 'junk.root')"
big_dataset = "rucio://mc15_13TeV:mc15_13TeV.361106.PowhegPythia8EvtGen_AZNLOCTEQ6L1_Zee.merge.DAOD_STDM3.e3601_s2576_s2132_r6630_r6264_p2363_tid05630052_00?files=3"
dataset = "mc16_13TeV:DAOD_TOPQ1.25521529._000009.pool.root.1"
ds = ServiceXSourceXAOD(dataset)
leptons_per_event_query = ds \
        .Select(lambda e: e.Electrons("Electrons")) \
        .Select(lambda eles: eles.Where(lambda e: e.pt()/1000.0 > 30.0)) \
        .Select(lambda eles: eles.Where(lambda e: abs(e.eta()) < 2.5)) \
        .Where(lambda eles: len(eles) == 2) \
        .Select(lambda ls: (ls.Select(lambda e: e.pt()/1000.0), ls.Select(lambda e: e.eta()), ls.Select(lambda e: e.phi()), ls.Select(lambda e: e.m()/1000.0), ls.Select(lambda e: e.charge())))

print(leptons_per_event_query.AsPandasDF(['electrons_pt', 'electrons_eta', 'electrons_phi', 'electrons_mass', 'electrons_charge']).value())

**Expected behavior**
I am expected to have a PandasDF with multiple parameters. 

**Screenshots**
<img width="1237" alt="image" src="https://github.com/ssl-hep/ServiceX/assets/16172918/167150d9-9e0c-40cd-8c2b-6e251464c118">

**Additional context**
Any other runnable example with multiple parameters selection ?

**Comment by ponyisi** [comment]
Did you find a solution?

**Comment by ponyisi** [comment]
Reported resolved
