### ISSUE TITLE
sleep in shutdown_transformer_job

### ISSUE THREAD

**Issue by ivukotic** [ssl-hep/ServiceX#717]
There is a time.sleep of 10 seconds in the shutdown_transformer_job. This is called synchronously, so when we have 5-10 concurrent requests that finish close in time, it completely blocks the server (we are running with 5 workers).

We need to make sure that the TransformerFileComplete put is called only once output data is surely in s3 and then we don't need that wait.

**Comment by BenGalewsky** [comment]
Closed via #748
