### ISSUE TITLE
Secure Kafka

### ISSUE THREAD

**Issue by BenGalewsky** [ssl-hep/ServiceX#72]
# Story
_As an analyzer I want to securely access the SSL Kafka cluster so I can access transformed events from anywhere_

# Assumptions
1. Enable certs in front of the Kafka Brokers
2. Deployed with remote access and a well known DNS name

# Acceptance Criteria
1. Given I have a valid Kafka Cert When I attempt to read messages from outside of the Kubernetes cluster Then I should receive messages.
2. Given I don't have a valid Kafka Cert When I attempt to read messages from outside the kubernetes cluster then I should receive an error

**Comment by robrwg** [comment]
Can we have a bit more of a technical description of what's needed here, on both server-side and client-side?
