### ISSUE TITLE
Add Kafka to ServiceX Helm Chart

### ISSUE THREAD

**Issue by BenGalewsky** [ssl-hep/ServiceX#73]
# Story
_As an SSL administrator I want to deploy Kafka along with ServiceX so I can stream transformed events_

# Assumptions
1. Not accessible outside of cluster
2. Includes Kafka dashboard which will have an ingres

# Acceptance Criteria
1. Given I have enabled Kafka in values.yaml When I install the helm chart Then I should be able to send and receive messages with Kafka from inside the cluster And I should be able to log into the dashboard

**Comment by robrwg** [comment]
Okay - I understand this is in review.  How do we move forward, if the chart is reliable and ready.

**Comment by robrwg** [comment]
Do we need to have a mega-chart for ServiceX?  How different is the ServiceX Helm chart from https://hub.helm.sh/charts/incubator/kafka ?
