### ISSUE TITLE
Apply Selections in Transformer

### ISSUE THREAD

**Issue by BenGalewsky** [ssl-hep/ServiceX#75]
# Story
_As an analyzer I want to apply computationally simple selections to transformed events so I can reduce the amount of data delivered_

Example:
```
passEventCleaning&&trilep_type>0&&(lep_Pt_0>10e3&&lep_Pt_1>20e3&&lep_Pt_2>20e3)&&
(lep_isTrigMatch_0||lep_isTrigMatch_1||lep_isTrigMatch_2||matchDLTll01||matchDLTll02||matchDLTll12)&&
abs(total_charge)==1&&(((lep_ID_0==-lep_ID_1 && ((lep_ID_0==-lep_ID_1&&abs(Mll01-91.2e3)<10e3)))||
(lep_ID_0==-lep_ID_2&&abs(Mll02-91.2e3)<10e3)))&&(lep_ID_0!=-lep_ID_1||(Mll01>12e3))
&&(lep_ID_0!=-lep_ID_2||(Mll02>12e3))&&( ( (abs(lep_ID_0) == 13 &&lep_isMedium_0) ||
( abs( lep_ID_0 ) == 11&&abs( lep_Eta_0 ) <2.0)) && ((abs( lep_ID_1 ) == 11&&abs( lep_Eta_1 ) <2.0)|| 
(abs(lep_ID_1) == 13 && lep_isMedium_1) ) && ((abs( lep_ID_2 ) == 11&&abs( lep_Eta_2 ) <2.0)||
(abs( lep_ID_2 ) == 13 && lep_isMedium_2)))&&nJets_OR_T>0
&&abs(Mlll012-91.2e3)>10e3&&best_Z_other_MtLepMet>30e3&&MET_RefFinal_et>20e3&&lep_Pt_3==0
```

# Assumptions
1. Python predicate provided as `selection` property in transform request
2. Should work in Uproot and pyRoot implementations on the awkward array

# Acceptance Criteria
1. Given I have a transform request with a python predicate When I submit the transform then I only see events that pass the selection in my result

**Comment by gordonwatts** [comment]
This is related to the ast-language work, is that right? Do the selections have to be the format specified for this? Or can they be closer to what we've been thinking about for the ast-language work?

**Comment by BenGalewsky** [comment]
This select needs to be edited to show what it would look like in func_adl - that's what will be implemented

**Comment by BenGalewsky** [comment]
Going to close this since this is really covered by funcADL transformers! Go @gordonwatts and @masonproffitt !
