### ISSUE TITLE
did-finder image does not get rebuilt correctly

### ISSUE THREAD

**Issue by ivukotic** [ssl-hep/ServiceX#797]
All of the servicex' at river-dev are not working since they use wrong rucio auth server.

did-finder image is based on rucio-client image. Rucio-client image has been updated. rucio-did-finder image has been rebuilt but it still uses old rucio-client image as the base.

**Comment by ponyisi** [comment]
Hi @ivukotic , things seem to be working - was this fixed?

**Comment by ivukotic** [comment]
I did not fix it. It could be that the github cache just expired and it got new image?

**Comment by ponyisi** [comment]
Seems ok now.
