### ISSUE TITLE
UprootRaw needs protection against empty branch

### ISSUE THREAD

**Issue by kyungeonchoi** [ssl-hep/ServiceX#807]
**Describe the bug**
Transformation crashed if an accessed tree has no entry or no entry left after cut

**To Reproduce**
Deliver column (`el_pt`) from tree (`nominal`) from a file with no entry (`user.mgeyik:user.mgeyik.30182995._000042.out.root`)

**Expected behavior**
Transformation runs successfully and returns an empty array

**Additional context**
I haven't tested against Uproot FuncADL transformer yet but it might be the same situation

**Comment by ponyisi** [comment]
A zero entry but well-defined tree should work already in the current version of the UprootRaw transformer. Please post the query that fails (preferably with a transformation ID).
