### ISSUE TITLE
DID lookup cache storing expired grid location for file.

### ISSUE THREAD

**Issue by marctost11** [ssl-hep/ServiceX#834]
I am trying to deliver some files from the grid. I get a file lookup error (attached below). I strongly suspect this is because I attempted a previous delivery, when the files were located on a scratch disk, the the path has since expired. The file still exists, but with a different location. A flag to allow the user to re-run the DID lookup stage would be a useful addition to address this.

> Failed to transform input file root://lcg-dp11.sfu.computecanada.ca:1094/atlas/atlasscratchdisk/rucio/user/mtost/3d/95/user.mtost.40624683._000329.add_HF_info_add_exclude.root: File did not open properly: [FATAL] Auth failed: No protocols left to try
> Traceback (most recent call last):
>   File "/generated/transform_single_file.py", line 22, in transform_single_file
>     awkward_array_dict, histograms = generated_transformer.run_query(file_path)
>                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/generated/..2024_09_04_14_05_46.1599208375/generated_transformer.py", line 7, in run_query
>     a, b = run_single_query(file_path, subquery)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/generated/..2024_09_04_14_05_46.1599208375/generated_transformer.py", line 69, in run_single_query
>     with uproot.open({file_path: None}) as fl:
>          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/conda/lib/python3.12/site-packages/uproot/reading.py", line 142, in open
>     file = ReadOnlyFile(
>            ^^^^^^^^^^^^^
>   File "/opt/conda/lib/python3.12/site-packages/uproot/reading.py", line 561, in __init__
>     self._source = source_cls(file_path, **self._options)
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/conda/lib/python3.12/site-packages/uproot/source/fsspec.py", line 45, in __init__
>     self._open()
>   File "/opt/conda/lib/python3.12/site-packages/uproot/source/fsspec.py", line 59, in _open
>     self._file = self._fs.open(self._file_path)
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/conda/lib/python3.12/site-packages/fsspec_xrootd/xrootd.py", line 706, in open
>     f = self._open(
>         ^^^^^^^^^^^
>   File "/opt/conda/lib/python3.12/site-packages/fsspec_xrootd/xrootd.py", line 663, in _open
>     return XRootDFile(
>            ^^^^^^^^^^^
>   File "/opt/conda/lib/python3.12/site-packages/fsspec_xrootd/xrootd.py", line 768, in __init__
>     raise OSError(f"File did not open properly: {status.message}")
> OSError: File did not open properly: [FATAL] Auth failed: No protocols left to try
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/generated/transform_single_file.py", line 85, in <module>
>     transform_single_file(sys.argv[1], Path(sys.argv[2]), sys.argv[3])
>   File "/generated/transform_single_file.py", line 79, in transform_single_file
>     raise RuntimeError(mesg)
> RuntimeError: Failed to transform input file root://lcg-dp11.sfu.computecanada.ca:1094/atlas/atlasscratchdisk/rucio/user/mtost/3d/95/user.mtost.40624683._000329.add_HF_info_add_exclude.root: File did not open properly: [FATAL] Auth failed: No protocols left to try

**Comment by BenGalewsky** [comment]
Fixed through manual clearing of dataset record from db
