### ISSUE TITLE
Deleting the helm chart while transformers are running leaves them running

### ISSUE THREAD

**Issue by gordonwatts** [ssl-hep/ServiceX#85]
**Describe the bug**
When one deletes a helm chart, it should remove everything, including the transformer pods/deployment started by the running chart.

**To Reproduce**
1. run servicex
2. submit a transform
3. while the transforms are in progress, delete the chart

**Expected behavior**
There should be no pods/etc/ left associated with the chart

**Comment by BenGalewsky** [comment]
Not a big use case... updates to the chart should be able to handle running transforms
