### ISSUE TITLE
Celery DID finder has an invalid call on fileset_complete

### ISSUE THREAD

**Issue by ponyisi** [ssl-hep/ServiceX#854]
`fileset_complete.py` has the following code:

```
            for transform_request in TransformRequest.lookup_pending_on_dataset(int(dataset_id)):
                dataset.publish_files(transform_request, self.lookup_result_processor)
                transform_request.status = TransformStatus.running
```

However `dataset` does not have the `publish_files` method, this is actually a method on `DatasetManager` and not `Dataset`. Whenever this codepath is hit, if there are pending lookups, the pending lookups will not be updated (and neither will the primary request!) (Not sure how this passed the linting ...)

**Comment by BenGalewsky** [comment]
> (Not sure how this passed the linting ...)

We'd need to introduce myPy to catch this. That will be a painful transition for sure
