### ISSUE TITLE
Allow DID finder to be configured with appropriate xcache

### ISSUE THREAD

**Issue by gordonwatts** [ssl-hep/ServiceX#87]
# Story
_As a administrator I want to deploy ServiceX to use my local XCache or not to use one at all so I can run efficiently or at the very least not burden someone else's XCache.

# Assumptions
1. I have access only to a `values.yaml` file which which I can modify the ServiceX chart values.
1. I can deploy a working ServiceX in my cluster.

# Acceptance Criteria
1. The raw chart will deploy and not use any XCache
1. With appropriate `values.yaml` it can be deployed to use an XCache instance, like that in MWT2.

**Comment by BenGalewsky** [comment]
It should just be modifying [a line](https://github.com/ssl-hep/ServiceX/blob/bd652d14cd39b31db53bad80858fbffb279dbc96/servicex/templates/did-finder-configmap.yaml#L16) in the template `did-finder-configmap.yaml`
