### ISSUE TITLE
Continuous Delivery of ServiceX

### ISSUE THREAD

**Issue by BenGalewsky** [ssl-hep/ServiceX#99]
# Story
_As a ServiceX Developer I want a running instance of the current develop branch of the ServiceX repo so I can be confident the code is correct_

# Assumptions
1. Deployment will run on River
2. Integration tests will be run against the deployment
3. There will be a dashboard of the current state
4. Failures will be reported to a slack channel

# Acceptance Criteria
1. I can connect to the deployed serviceX and run a transform
2. I can see the status of the builds in a dashboard
3. I can force a test breakage and see it reported in slack

**Comment by BenGalewsky** [comment]
Sounds like the best approach will follow the work done on SLATE - running Jenkins inside the River cluster and without external access.

For SLATE, they publish the logs only using nginx, and sending the URLs for them to Slack so the team can get at them easily.

There is a [helm chart](https://github.com/helm/charts/tree/master/stable/jenkins) for Jenkins

**Comment by BenGalewsky** [comment]
Actually FluxCD is the way to go: https://fluxcd.io

See this [great presentation](https://indico.cern.ch/event/882997/contributions/3720712/attachments/1983222/3303521/Managing_Helm_Deployments_with_GitOPS_at_CERN.pdf) that was given at the SSL meeting a few months ago:

**Comment by AndrewEckart** [comment]
Ran through the [flux-get-started](https://github.com/fluxcd/flux-get-started) tutorial. It worked, but it was a little heavy on my single-node local development cluster. We'll need to get this set up on RIVER.

**Comment by AndrewEckart** [comment]
Cross-posted from Slack:

It definitely seems like Flux v2 is the way to go for CD. I was able to configure my local development cluster to make an automatic deployment of ServiceX with the default values (no authentication).

There are a couple of issues that still need to be resolved:
- Flux can only deploy from a Helm repository. The latest version of the chart in our repository at ssl-hep/servicex is an RC3 release from September which is now somewhat dated (it still contains a buggy version of Minio which we replaced a while ago, for example). If we are only publishing the chart once every several months, then "continuous deployment" will not be continuous at all - it defeats the purpose. We really need to figure out our versioning. Every single change to the chart should be published immediately as a patch version, which is the pattern I've seen with other charts (e.g. Minio) - this also means dissociating the chart version and the app version.
- Flux has somewhat limited support for Helm values. You can specify values for a helm release, but they must be passed declaratively (i.e. written down in a file that is then passed into git). This makes it hard to store secrets, such as a Globus Client ID. So it might be hard to have Flux deliver an externally facing, production deployment - but that's not necessarily a bad thing. It would still be very useful to have a continuous deployment with the default values.
